"""
train.py — Master training script for the AML graph generation pipeline.
─────────────────────────────────────────────────────────────────────────────
Edit the CONFIG section below to choose your dataset, set file paths, and
tune hyperparameters.  Then run:

    python train.py                   # train both models (diffusion → simclr)
    python train.py --phase diffusion # diffusion only
    python train.py --phase simclr    # simclr only  (needs diffusion checkpoint)

Supported datasets
──────────────────
  ibm        IBM AML Transactions CSV (HI-Small, LI-Small, LI-Large, …)
  elliptic   Elliptic Bitcoin Dataset (auto-detected from ELLIPTIC_DATA_DIR)

Outputs
───────
  checkpoints/diffusion_ibm/model.pt       IBM diffusion checkpoint
  checkpoints/diffusion_elliptic/model.pt  Elliptic diffusion checkpoint
  checkpoints/simclr_ibm/best_model.pt     IBM SimCLR checkpoint
  checkpoints/simclr_elliptic/best_model.pt  Elliptic SimCLR checkpoint
"""

# ══════════════════════════════════════════════════════════════════════════════
#  CONFIG — edit this section
# ══════════════════════════════════════════════════════════════════════════════

# ── Dataset selection ─────────────────────────────────────────────────────────
DATASET = "ibm"           # "ibm"  or  "elliptic"

# ── IBM dataset settings ──────────────────────────────────────────────────────
IBM_CSV_PATH = r"C:\Users\lucsc\Thesis\grad\grad\data\IBM\LI-Small_Trans.csv"
IBM_MAX_NETWORKS   = 2000   # laundering networks extracted; same count of clean
IBM_MAX_DEPTH      = 4      # BFS depth for subgraph extraction
IBM_COLLAPSE_THRESH = 10    # hub-collapse threshold
IBM_MAX_NODES      = 300    # pad size for diffusion / encoder

# ── Elliptic dataset settings ─────────────────────────────────────────────────
# The adapter auto-detects the path; override ELLIPTIC_DATA_DIR if needed.
ELLIPTIC_DATA_DIR  = None   # None = auto-detect from data/elliptic_bitcoin_dataset
ELLIPTIC_MAX_NODES = 100    # ego subgraph cap
ELLIPTIC_DEPTH     = 4      # BFS hop depth around each anchor transaction

# ── Diffusion hyperparameters (IBM) ───────────────────────────────────────────
DIFF_IBM_EPOCHS      = 300
DIFF_IBM_BATCH       = 32
DIFF_IBM_LR          = 2e-4
DIFF_IBM_WARMUP      = 15
DIFF_IBM_HIDDEN      = 128
DIFF_IBM_TIMESTEPS   = 500
DIFF_IBM_ADJ_W       = 0.3
DIFF_IBM_DENSITY_W   = 3.0
DIFF_IBM_LAUND_W     = 2.0
DIFF_IBM_GRAD_CLIP   = 1.0

# ── Diffusion hyperparameters (Elliptic) ──────────────────────────────────────
DIFF_ELL_EPOCHS      = 200
DIFF_ELL_BATCH       = 32
DIFF_ELL_LR          = 2e-4
DIFF_ELL_WARMUP      = 10
DIFF_ELL_HIDDEN      = 128
DIFF_ELL_TIMESTEPS   = 500
DIFF_ELL_ADJ_W       = 0.3
DIFF_ELL_DENSITY_W   = 3.0
DIFF_ELL_LAUND_W     = 2.0
DIFF_ELL_GRAD_CLIP   = 1.0

# ── SimCLR hyperparameters (IBM) ──────────────────────────────────────────────
SIMCLR_IBM_EPOCHS      = 100
SIMCLR_IBM_BATCH       = 128
SIMCLR_IBM_LR          = 1e-3
SIMCLR_IBM_SUPCON_W    = 0.5
SIMCLR_IBM_SUPCON_T    = 0.07
SIMCLR_IBM_CKPT_EVERY  = 10
SIMCLR_IBM_P_DIFFUSION = 0.3   # fraction of views generated by diffusion
SIMCLR_IBM_T_FRAC      = 0.3   # noise level fraction for diffusion views

# ── SimCLR hyperparameters (Elliptic) ─────────────────────────────────────────
SIMCLR_ELL_EPOCHS      = 100
SIMCLR_ELL_BATCH       = 128
SIMCLR_ELL_LR          = 1e-3
SIMCLR_ELL_SUPCON_W    = 0.5
SIMCLR_ELL_SUPCON_T    = 0.07
SIMCLR_ELL_CKPT_EVERY  = 10
SIMCLR_ELL_P_EDGE_DROP = 0.20
SIMCLR_ELL_P_FEAT_MASK = 0.15
SIMCLR_ELL_P_DIFFUSION = 0.30

# ══════════════════════════════════════════════════════════════════════════════
#  Internals — do not edit below this line
# ══════════════════════════════════════════════════════════════════════════════

import argparse
import math
import os
import random
import sys
import time
from pathlib import Path
from torch.utils.data import Dataset, DataLoader

import torch
import torch.nn.functional as F

ROOT_DIR   = Path(__file__).resolve().parent   # igraph_version/
DIFF_DIR   = ROOT_DIR / "diffusion"
SIMCLR_DIR = ROOT_DIR / "simclr"
DATA_DIR   = ROOT_DIR / "data"
CKPT_DIR   = ROOT_DIR / "checkpoints"

for _p in (str(ROOT_DIR), str(DIFF_DIR), str(SIMCLR_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

# ─────────────────────────────────────────────────────────────────────────────
# IBM — diffusion training
# ─────────────────────────────────────────────────────────────────────────────

def train_diffusion_ibm(device):
    from diffusion.collate   import collate_fn
    from diffusion.dataset   import CachedDataset
    from diffusion.diff_util import create_diffusion, preprocess
    from diffusion.model     import DiffusionGNN
    from diffusion.resample  import LossSecondMomentResampler
    from diffusion.visualizations import run_all_visualizations
    from augmentation        import build_igraph_from_transactions
    from util import (preprocess_df, extract_networks_igraph)

    cache_path = DATA_DIR / "cached_dataset_ibm.pt"
    graphs_dir = str(DIFF_DIR / "graphs")
    out_path   = CKPT_DIR / "diffusion_ibm" / "model.pt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"IBM Diffusion Training   ({DIFF_IBM_EPOCHS} epochs)")
    print(f"  CSV  : {IBM_CSV_PATH}")
    print(f"  Save : {out_path}")
    print('='*60)

    NODE_DIM = 11  # laundering flag (1) + topology (5) + transaction features (5)

    def _needs_rebuild():
        if not cache_path.exists():
            return True
        s = torch.load(str(cache_path), weights_only=False)
        if len(s) == 0 or s[0][0].shape[1] != NODE_DIM:
            cache_path.unlink()
            return True
        return False

    if _needs_rebuild():
        print("Extracting IBM networks …")
        df_full  = preprocess_df(IBM_CSV_PATH)
        networks = extract_networks_igraph(
            df_full, max_depth=IBM_MAX_DEPTH,
            max_networks=IBM_MAX_NETWORKS * 2,
            collapse_threshold=IBM_COLLAPSE_THRESH,
            max_nodes=IBM_MAX_NODES,
        )
        for net in networks:
            net["graph"] = build_igraph_from_transactions(net["transactions"])
        print(f"  {len(networks)} networks extracted. Preprocessing …")
        preprocess(networks, save_path=str(cache_path))

    print(f"Loading cache: {cache_path}")
    dataset  = CachedDataset(str(cache_path))
    loader   = DataLoader(dataset, batch_size=DIFF_IBM_BATCH,
                          shuffle=True, collate_fn=collate_fn, drop_last=True)
    all_x    = torch.cat([x for x, _adj in dataset], dim=0)
    x_mean   = torch.zeros(NODE_DIM); x_std = torch.ones(NODE_DIM)
    x_mean[1:] = all_x[:, 1:].mean(0); x_std[1:] = all_x[:, 1:].std(0).clamp(min=1e-6)
    x_mean, x_std = x_mean.to(device), x_std.to(device)
    print(f"Dataset: {len(dataset)} graphs")

    model     = DiffusionGNN(node_dim=NODE_DIM, hidden_dim=DIFF_IBM_HIDDEN, num_layers=4).to(device)
    diffusion = create_diffusion(T=DIFF_IBM_TIMESTEPS)
    resampler = LossSecondMomentResampler(diffusion)
    optimizer = torch.optim.Adam(model.parameters(), lr=DIFF_IBM_LR)

    def _lr(ep):
        if ep < DIFF_IBM_WARMUP:
            return (ep + 1) / DIFF_IBM_WARMUP
        p = (ep - DIFF_IBM_WARMUP) / max(1, DIFF_IBM_EPOCHS - DIFF_IBM_WARMUP)
        return 0.5 * (1.0 + math.cos(math.pi * p))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, _lr)
    use_amp   = (str(device) == "cuda")
    scaler    = torch.amp.GradScaler("cuda", enabled=use_amp)
    t0        = time.time()

    for epoch in range(DIFF_IBM_EPOCHS):
        model.train()
        total = 0.0; nb = 0

        for x_batch, adj_batch, mask in loader:
            x_batch   = x_batch.to(device)
            adj_batch = adj_batch.to(device)
            mask      = mask.to(device)
            n_nodes   = x_batch.shape[1]

            x_norm = x_batch.clone()
            x_norm[:, :, 1:] = (x_batch[:, :, 1:] - x_mean[1:]) / x_std[1:]
            x_norm = x_norm * mask.unsqueeze(-1)

            t, weights = resampler.sample(x_batch.shape[0], device)
            with torch.autocast("cuda", enabled=use_amp):
                x_t, adj_t = diffusion.q_sample(x_norm, t, node_mask=mask, adj_start=adj_batch)
                eps_pred, adj_pred, node_pred = model(x_t, diffusion._scale_timesteps(t),
                                                      adj=adj_t, node_mask=mask)
                # noise-pred loss on continuous features
                noise_true = x_t[:, :, 1:] - x_norm[:, :, 1:]
                mse = ((eps_pred[:, :, 1:] - noise_true) ** 2 * mask.unsqueeze(-1)).sum() / mask.sum().clamp(1)

            # BCE losses computed in float32 — bce is unsafe inside autocast
            eps_pred_f = eps_pred.float()
            adj_pred_f = adj_pred.float()
            mask_f     = mask.float()
            bce  = F.binary_cross_entropy(
                eps_pred_f[:, :, 0].clamp(1e-6, 1-1e-6) * mask_f,
                x_batch[:, :, 0].float() * mask_f, reduction="sum"
            ) / mask_f.sum().clamp(1)
            _m2 = mask_f[:, :, None] * mask_f[:, None, :]
            adj_l = F.binary_cross_entropy(
                adj_pred_f.clamp(1e-6, 1-1e-6) * _m2,
                adj_batch.float() * _m2, reduction="sum"
            ) / (_m2.sum()).clamp(1)
            pred_dens = adj_pred_f.sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            true_dens = adj_batch.float().sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            dens_loss = ((pred_dens - true_dens) ** 2).mean()

            loss = (mse + DIFF_IBM_LAUND_W * bce
                    + DIFF_IBM_ADJ_W * adj_l
                    + DIFF_IBM_DENSITY_W * dens_loss)

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), DIFF_IBM_GRAD_CLIP)
            scaler.step(optimizer); scaler.update()
            total += loss.item(); nb += 1

        scheduler.step()
        if (epoch + 1) % 10 == 0 or epoch < 3:
            print(f"Epoch {epoch+1:4d}/{DIFF_IBM_EPOCHS} | "
                  f"loss={total/max(nb,1):.4f} | lr={scheduler.get_last_lr()[0]:.2e} | "
                  f"{time.time()-t0:.0f}s")

        torch.save({"model": model.state_dict(),
                    "x_mean": x_mean.cpu(), "x_std": x_std.cpu()}, out_path)

    print(f"\nIBM diffusion checkpoint saved → {out_path}")


# ─────────────────────────────────────────────────────────────────────────────
# IBM — SimCLR training
# ─────────────────────────────────────────────────────────────────────────────

def train_simclr_ibm(device):
    from simclr import GraphEncoder, ProjectionHead, train_simclr_fast
    from augmentation import build_igraph_from_transactions
    from util import (preprocess_df, extract_networks_igraph)
    from diffusion.model     import DiffusionGNN
    from diffusion.diff_util import create_diffusion

    ckpt_dir  = CKPT_DIR / "simclr_ibm"
    diff_ckpt = CKPT_DIR / "diffusion_ibm" / "model.pt"
    cache_pt  = DATA_DIR / "simclr_networks_cache.pt"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"IBM SimCLR Training   ({SIMCLR_IBM_EPOCHS} epochs)")
    print(f"  CSV  : {IBM_CSV_PATH}")
    print(f"  Save : {ckpt_dir}")
    print('='*60)

    def _cache_stale(nets):
        """Return True if the cached networks have the wrong node feature dim."""
        for n in nets:
            xd = n.get("x_dense")
            if xd is not None:
                return xd.shape[1] != 11
        return False  # no x_dense yet — will be built on first use

    networks = None
    if cache_pt.exists():
        print(f"Loading networks from cache: {cache_pt}")
        networks = torch.load(str(cache_pt), weights_only=False)
        if _cache_stale(networks):
            print("  Stale cache (wrong node_dim) — rebuilding …")
            cache_pt.unlink()
            networks = None

    if networks is None:
        print("Extracting IBM networks …")
        df_full  = preprocess_df(IBM_CSV_PATH)
        networks = extract_networks_igraph(
            df_full, max_depth=IBM_MAX_DEPTH,
            max_networks=IBM_MAX_NETWORKS * 2,
            collapse_threshold=IBM_COLLAPSE_THRESH,
            max_nodes=IBM_MAX_NODES,
        )
        for net in networks:
            net["graph"] = build_igraph_from_transactions(net["transactions"])
        torch.save(networks, str(cache_pt))
        print(f"Saved cache → {cache_pt}")
    print(f"  {len(networks)} networks loaded")

    # Load optional diffusion model for augmentation
    diff_model = diffusion = x_mean = x_std = None
    if diff_ckpt.exists():
        ckpt       = torch.load(str(diff_ckpt), map_location=device, weights_only=False)
        node_dim_ckpt = ckpt["model"]["input_proj.weight"].shape[1]
        diff_model = DiffusionGNN(node_dim=node_dim_ckpt, hidden_dim=DIFF_IBM_HIDDEN, num_layers=4).to(device)
        diff_model.load_state_dict(ckpt["model"])
        diff_model.eval()
        diffusion = create_diffusion(T=DIFF_IBM_TIMESTEPS)
        x_mean    = ckpt["x_mean"].to(device)
        x_std     = ckpt["x_std"].to(device)
        print(f"  Diffusion augmentation enabled (node_dim={node_dim_ckpt}).")
    else:
        node_dim_ckpt = 11  # default to current feature count
        print(f"  Diffusion checkpoint not found at {diff_ckpt} — training without augmentation.")

    encoder   = GraphEncoder(in_dim=node_dim_ckpt, hidden_dim=64, out_dim=128).to(device)
    projector = ProjectionHead(in_dim=128, proj_dim=64).to(device)
    optimizer = torch.optim.Adam(
        list(encoder.parameters()) + list(projector.parameters()), lr=SIMCLR_IBM_LR
    )

    train_simclr_fast(
        networks=networks, full_df=None,
        encoder=encoder, projector=projector, optimizer=optimizer,
        device=device,
        batch_size=SIMCLR_IBM_BATCH,
        epochs=SIMCLR_IBM_EPOCHS,
        checkpoint_dir=str(ckpt_dir),
        diffusion_model=diff_model, diffusion=diffusion,
        x_mean=x_mean, x_std=x_std,
        p_diffusion=SIMCLR_IBM_P_DIFFUSION,
        diffusion_t_frac=SIMCLR_IBM_T_FRAC,
        max_nodes=IBM_MAX_NODES,
    )
    print(f"\nIBM SimCLR checkpoints saved → {ckpt_dir}")


# ─────────────────────────────────────────────────────────────────────────────
# Elliptic — diffusion training
# ─────────────────────────────────────────────────────────────────────────────

def train_diffusion_elliptic(device):
    from diffusion.collate   import collate_fn
    from diffusion.diff_util import create_diffusion
    from diffusion.model     import DiffusionGNN
    from diffusion.resample  import LossSecondMomentResampler
    from data.elliptic_adapter import load_elliptic_pyg_graphs

    cache_path = DATA_DIR / "elliptic_diffusion_cache_d4.pt"
    out_path   = CKPT_DIR / "diffusion_elliptic" / "model.pt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"Elliptic Diffusion Training   ({DIFF_ELL_EPOCHS} epochs)")
    print(f"  max_nodes={ELLIPTIC_MAX_NODES}  depth={ELLIPTIC_DEPTH}")
    print(f"  Save : {out_path}")
    print('='*60)

    NODE_DIM = 6

    def _pyg_to_dense(data):
        n = data.x.shape[0]
        x = torch.zeros(n, NODE_DIM)
        x[:, 0] = float(data.y.item())
        x[:, 1:] = data.x
        adj = torch.zeros(n, n)
        ei = data.edge_index
        if ei.shape[1] > 0:
            valid = ei[0] != ei[1]
            src, dst = ei[0][valid], ei[1][valid]
            inb = (src < n) & (dst < n)
            adj[src[inb], dst[inb]] = 1.0
        return x, adj

    if not cache_path.exists():
        kwargs = dict(max_nodes=ELLIPTIC_MAX_NODES, depth=ELLIPTIC_DEPTH)
        if ELLIPTIC_DATA_DIR:
            kwargs["data_dir"] = ELLIPTIC_DATA_DIR
        raw = load_elliptic_pyg_graphs(**kwargs)
        pairs = [(x, a) for g in raw for x, a in [_pyg_to_dense(g)] if g.x.shape[0] >= 3]
        torch.save(pairs, str(cache_path))
        print(f"Saved {len(pairs)} dense pairs → {cache_path}")
    else:
        pairs = torch.load(str(cache_path), weights_only=False)
        if len(pairs) == 0 or pairs[0][0].shape[1] != NODE_DIM:
            cache_path.unlink()
            return train_diffusion_elliptic(device)

    pairs = [(x, a) for x, a in pairs if x.shape[0] <= ELLIPTIC_MAX_NODES]
    print(f"Dataset: {len(pairs)} graphs")

    class _DS(Dataset):
        def __getitem__(self, i): return pairs[i]
        def __len__(self): return len(pairs)

    loader   = DataLoader(_DS(), batch_size=DIFF_ELL_BATCH,
                          shuffle=True, collate_fn=collate_fn, drop_last=True)
    all_x    = torch.cat([x for x, _ in pairs], dim=0)
    x_mean   = torch.zeros(NODE_DIM); x_std = torch.ones(NODE_DIM)
    x_mean[1:] = all_x[:, 1:].mean(0); x_std[1:] = all_x[:, 1:].std(0).clamp(min=1e-6)
    x_mean, x_std = x_mean.to(device), x_std.to(device)

    model     = DiffusionGNN(node_dim=NODE_DIM, hidden_dim=DIFF_ELL_HIDDEN, num_layers=4).to(device)
    diffusion = create_diffusion(T=DIFF_ELL_TIMESTEPS)
    resampler = LossSecondMomentResampler(diffusion)
    optimizer = torch.optim.Adam(model.parameters(), lr=DIFF_ELL_LR)

    def _lr(ep):
        if ep < DIFF_ELL_WARMUP:
            return (ep + 1) / DIFF_ELL_WARMUP
        p = (ep - DIFF_ELL_WARMUP) / max(1, DIFF_ELL_EPOCHS - DIFF_ELL_WARMUP)
        return 0.5 * (1.0 + math.cos(math.pi * p))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, _lr)
    use_amp   = (str(device) == "cuda")
    scaler    = torch.amp.GradScaler("cuda", enabled=use_amp)
    t0        = time.time()

    for epoch in range(DIFF_ELL_EPOCHS):
        model.train()
        total = 0.0; nb = 0

        for x_batch, adj_batch, mask in loader:
            x_batch   = x_batch.to(device)
            adj_batch = adj_batch.to(device)
            mask      = mask.to(device)
            n_nodes   = x_batch.shape[1]

            x_norm = x_batch.clone()
            x_norm[:, :, 1:] = (x_batch[:, :, 1:] - x_mean[1:]) / x_std[1:]
            x_norm = x_norm * mask.unsqueeze(-1)

            t, _ = resampler.sample(x_batch.shape[0], device)
            with torch.autocast("cuda", enabled=use_amp):
                x_t, adj_t = diffusion.q_sample(x_norm, t, node_mask=mask, adj_start=adj_batch)
                eps_pred, adj_pred, _ = model(x_t, diffusion._scale_timesteps(t),
                                              adj=adj_t, node_mask=mask)
                noise_true = x_t[:, :, 1:] - x_norm[:, :, 1:]
                mse = ((eps_pred[:, :, 1:] - noise_true) ** 2 * mask.unsqueeze(-1)).sum() / mask.sum().clamp(1)

            # BCE losses computed in float32 — bce is unsafe inside autocast
            eps_pred_f = eps_pred.float()
            adj_pred_f = adj_pred.float()
            mask_f     = mask.float()
            bce  = F.binary_cross_entropy(
                eps_pred_f[:, :, 0].clamp(1e-6, 1-1e-6) * mask_f,
                x_batch[:, :, 0].float() * mask_f, reduction="sum"
            ) / mask_f.sum().clamp(1)
            _m2 = mask_f[:, :, None] * mask_f[:, None, :]
            adj_l = F.binary_cross_entropy(
                adj_pred_f.clamp(1e-6, 1-1e-6) * _m2,
                adj_batch.float() * _m2, reduction="sum"
            ) / (_m2.sum()).clamp(1)
            pred_dens = adj_pred_f.sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            true_dens = adj_batch.float().sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            dens_loss = ((pred_dens - true_dens) ** 2).mean()
            loss = (mse + DIFF_ELL_LAUND_W * bce
                    + DIFF_ELL_ADJ_W * adj_l
                    + DIFF_ELL_DENSITY_W * dens_loss)

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), DIFF_ELL_GRAD_CLIP)
            scaler.step(optimizer); scaler.update()
            total += loss.item(); nb += 1

        scheduler.step()
        if (epoch + 1) % 10 == 0 or epoch < 3:
            print(f"Epoch {epoch+1:4d}/{DIFF_ELL_EPOCHS} | "
                  f"loss={total/max(nb,1):.4f} | {time.time()-t0:.0f}s")

        torch.save({"model": model.state_dict(),
                    "x_mean": x_mean.cpu(), "x_std": x_std.cpu()}, out_path)

    print(f"\nElliptic diffusion checkpoint saved → {out_path}")


# ─────────────────────────────────────────────────────────────────────────────
# Elliptic — SimCLR training
# ─────────────────────────────────────────────────────────────────────────────

def train_simclr_elliptic(device):
    from simclr import GraphEncoder, ProjectionHead, nt_xent_loss, sup_con_loss
    from torch_geometric.data import Data, Batch
    from diffusion.model     import DiffusionGNN
    from diffusion.diff_util import create_diffusion
    from data.elliptic_adapter import load_elliptic_pyg_graphs

    ckpt_dir  = CKPT_DIR / "simclr_elliptic"
    diff_ckpt = CKPT_DIR / "diffusion_elliptic" / "model.pt"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"Elliptic SimCLR Training   ({SIMCLR_ELL_EPOCHS} epochs)")
    print(f"  max_nodes={ELLIPTIC_MAX_NODES}  depth={ELLIPTIC_DEPTH}")
    print(f"  Save : {ckpt_dir}")
    print('='*60)

    # ── load data ──────────────────────────────────────────────────────────────
    kwargs = dict(max_nodes=ELLIPTIC_MAX_NODES, depth=ELLIPTIC_DEPTH)
    if ELLIPTIC_DATA_DIR:
        kwargs["data_dir"] = ELLIPTIC_DATA_DIR
    raw_graphs = load_elliptic_pyg_graphs(**kwargs)

    def _extend_6d(g):
        n = g.x.shape[0]
        lc = torch.full((n, 1), float(g.y.item()))
        x6 = torch.cat([lc, g.x], dim=1)
        return Data(x=x6, edge_index=g.edge_index.clone(), y=g.y.clone())

    graphs = [_extend_6d(g) for g in raw_graphs]
    n_ill  = sum(g.y.item() == 1 for g in graphs)
    print(f"  {len(graphs)} graphs ({n_ill} illicit, {len(graphs)-n_ill} licit)")

    # ── load optional diffusion model ──────────────────────────────────────────
    diff_model = diffusion = x_mean = x_std = None
    if diff_ckpt.exists():
        ckpt       = torch.load(str(diff_ckpt), map_location=device, weights_only=False)
        diff_model = DiffusionGNN(node_dim=6, hidden_dim=DIFF_ELL_HIDDEN, num_layers=4).to(device)
        diff_model.load_state_dict(ckpt["model"])
        diff_model.eval()
        diffusion = create_diffusion(T=DIFF_ELL_TIMESTEPS)
        x_mean    = ckpt["x_mean"].to(device)
        x_std     = ckpt["x_std"].to(device)
        print("  Diffusion augmentation enabled.")
    else:
        print(f"  Diffusion checkpoint not found at {diff_ckpt} — structural augmentation only.")

    # ── augmentations ──────────────────────────────────────────────────────────
    def _augment(g, p_edge=SIMCLR_ELL_P_EDGE_DROP, p_feat=SIMCLR_ELL_P_FEAT_MASK):
        x = g.x.clone()
        mask = torch.rand(x.shape[0], x.shape[1] - 1) > p_feat
        x[:, 1:] *= mask.float()
        ei = g.edge_index
        if ei.shape[1] > 0:
            n_edges  = ei.shape[1] // 2
            keep     = torch.rand(n_edges) > p_edge
            keep_idx = keep.repeat_interleave(2).nonzero(as_tuple=False).squeeze(1)
            if len(keep_idx) > 0:
                ei = ei[:, keep_idx]
            else:
                ei = torch.zeros(2, 0, dtype=torch.long)
        return Data(x=x, edge_index=ei, y=g.y.clone())

    def _diff_view(g):
        if diff_model is None:
            return None
        n = g.x.shape[0]
        x_pad  = torch.zeros(1, ELLIPTIC_MAX_NODES, 6, device=device)
        a_pad  = torch.zeros(1, ELLIPTIC_MAX_NODES, ELLIPTIC_MAX_NODES, device=device)
        msk    = torch.zeros(1, ELLIPTIC_MAX_NODES, device=device)
        x_pad[0, :n]     = g.x.to(device)
        msk[0, :n]       = 1.0
        ei = g.edge_index
        if ei.shape[1] > 0:
            valid = ei[0] != ei[1]
            s, d  = ei[0][valid], ei[1][valid]
            inb   = (s < n) & (d < n)
            a_pad[0, s[inb], d[inb]] = 1.0
        x_n = x_pad.clone()
        x_n[:, :, 1:] = (x_pad[:, :, 1:] - x_mean[1:]) / x_std[1:]
        x_n = x_n * msk.unsqueeze(-1)
        t_frac = random.uniform(0.1, 0.4)
        t_val  = max(1, int(t_frac * DIFF_ELL_TIMESTEPS))
        t      = torch.tensor([t_val], device=device)
        x_t, adj_t = diffusion.q_sample(x_n, t, node_mask=msk, adj_start=a_pad)
        try:
            with torch.no_grad():
                ep, ap, _ = diff_model(x_t, diffusion._scale_timesteps(t),
                                       adj=adj_t, node_mask=msk)
                x0_c = diffusion._predict_xstart_from_eps(x_t[..., 1:], t, ep[..., 1:])
                x0_b = ep[..., 0:1].clamp(0.0, 1.0)
            x0     = torch.cat([x0_b, x0_c], dim=-1)[0, :n].cpu()
            x0[:, 1:] = x0[:, 1:] * x_std[1:].cpu() + x_mean[1:].cpu()
            deg    = ap[0, :n, :n].cpu().sum(-1)
            x0[:, 1] = deg / deg.max().clamp(min=1.0)
            ei_out = (ap[0, :n, :n].cpu() > 0.5).nonzero(as_tuple=False).T.contiguous()
            return Data(x=x0, edge_index=ei_out, y=g.y.clone())
        except Exception:
            return None

    # ── training loop ──────────────────────────────────────────────────────────
    encoder   = GraphEncoder(in_dim=6, hidden_dim=64, out_dim=128).to(device)
    projector = ProjectionHead(in_dim=128, proj_dim=64).to(device)
    optimizer = torch.optim.Adam(
        list(encoder.parameters()) + list(projector.parameters()), lr=SIMCLR_ELL_LR
    )

    best_loss = float("inf")
    t0        = time.time()

    for epoch in range(SIMCLR_ELL_EPOCHS):
        encoder.train(); projector.train()
        if diff_model: diff_model.eval()
        random.shuffle(graphs)
        total = nx_t = sc_t = 0.0; nb = 0

        for i in range(0, len(graphs), SIMCLR_ELL_BATCH):
            batch = graphs[i : i + SIMCLR_ELL_BATCH]
            v1, v2, lbls = [], [], []
            for g in batch:
                v1.append(_augment(g))
                if diff_model and random.random() < SIMCLR_ELL_P_DIFFUSION:
                    dv = _diff_view(g)
                    v2.append(dv if dv is not None else _augment(g))
                else:
                    v2.append(_augment(g))
                lbls.append(int(g.y.item()))

            labels = torch.tensor(lbls, dtype=torch.long, device=device)
            b1 = Batch.from_data_list(v1).to(device)
            b2 = Batch.from_data_list(v2).to(device)

            optimizer.zero_grad()
            h1 = encoder(b1); h2 = encoder(b2)
            z1 = projector(h1); z2 = projector(h2)
            ntxent = nt_xent_loss(z1, z2)
            z_all  = torch.cat([z1, z2]); lbl_all = torch.cat([labels, labels])
            sc     = sup_con_loss(z_all, lbl_all, temperature=SIMCLR_ELL_SUPCON_T)
            loss   = ntxent + SIMCLR_ELL_SUPCON_W * sc
            loss.backward(); optimizer.step()

            total += loss.item(); nx_t += ntxent.item()
            sc_t  += sc.item() if isinstance(sc, torch.Tensor) else float(sc)
            nb    += 1

        avg = total / max(nb, 1)
        print(f"Epoch {epoch+1:3d}/{SIMCLR_ELL_EPOCHS} | "
              f"loss={avg:.4f} (nt_xent={nx_t/max(nb,1):.4f}, supcon={sc_t/max(nb,1):.4f}) | "
              f"{time.time()-t0:.1f}s")

        if (epoch + 1) % SIMCLR_ELL_CKPT_EVERY == 0:
            torch.save({"encoder_state_dict": encoder.state_dict(),
                        "projector_state_dict": projector.state_dict(),
                        "loss": avg, "epoch": epoch + 1},
                       ckpt_dir / f"epoch_{epoch+1}.pt")

        if avg < best_loss:
            best_loss = avg
            torch.save({"encoder_state_dict": encoder.state_dict(),
                        "projector_state_dict": projector.state_dict(),
                        "loss": avg, "epoch": epoch + 1},
                       ckpt_dir / "best_model.pt")

    print(f"\nElliptic SimCLR checkpoints saved → {ckpt_dir}  (best loss={best_loss:.4f})")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="AML graph generation — master training script")
    parser.add_argument("--dataset", choices=["ibm", "elliptic"], default=DATASET,
                        help=f"Dataset to train on (default: {DATASET})")
    parser.add_argument("--phase", choices=["diffusion", "simclr", "all"], default="all",
                        help="Which phase to run (default: all)")
    parser.add_argument("--ibm-csv", type=str, default=None,
                        help="Override IBM CSV path (overrides IBM_CSV_PATH in CONFIG)")
    args = parser.parse_args()

    if args.ibm_csv:
        global IBM_CSV_PATH
        IBM_CSV_PATH = args.ibm_csv

    dataset = args.dataset
    device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device  : {device}")
    print(f"Dataset : {dataset}")
    print(f"Phase   : {args.phase}")

    if dataset == "ibm":
        if args.phase in ("diffusion", "all"):
            train_diffusion_ibm(device)
        if args.phase in ("simclr", "all"):
            train_simclr_ibm(device)
    else:
        if args.phase in ("diffusion", "all"):
            train_diffusion_elliptic(device)
        if args.phase in ("simclr", "all"):
            train_simclr_elliptic(device)

    print("\nTraining complete.")


if __name__ == "__main__":
    main()
