"""
train.py — Master training script for the AML graph generation pipeline.
─────────────────────────────────────────────────────────────────────────────
Edit the CONFIG section below to choose your dataset, set file paths, and
tune hyperparameters.  Then run:

    python train.py                   # train both models (diffusion → simclr)
    python train.py --phase diffusion # diffusion only
    python train.py --phase simclr    # simclr only  (needs diffusion checkpoint)

Supported datasets
──────────────────
  ibm        IBM AML Transactions CSV (HI-Small, LI-Small, LI-Large, …)
  elliptic   Elliptic Bitcoin Dataset (auto-detected from ELLIPTIC_DATA_DIR)

Outputs
───────
  checkpoints/diffusion_ibm/model.pt       IBM diffusion checkpoint
  checkpoints/diffusion_elliptic/model.pt  Elliptic diffusion checkpoint
  checkpoints/simclr_ibm/best_model.pt     IBM SimCLR checkpoint
  checkpoints/simclr_elliptic/best_model.pt  Elliptic SimCLR checkpoint
"""

from pathlib import Path   # needed by CONFIG paths below

# ══════════════════════════════════════════════════════════════════════════════
#  CONFIG — edit this section
# ══════════════════════════════════════════════════════════════════════════════

# ── Dataset selection ─────────────────────────────────────────────────────────
DATASET = "elliptic"           # "ibm", "elliptic", or "ethereum"

# ── IBM dataset settings ──────────────────────────────────────────────────────
IBM_CSV_PATH = str(Path(__file__).resolve().parent.parent / "data" / "IBM" / "LI-Small_Trans.csv")
IBM_MAX_NETWORKS   = 2000   # laundering networks extracted; same count of clean
IBM_MAX_DEPTH      = 4      # BFS depth for subgraph extraction
IBM_COLLAPSE_THRESH = 10    # hub-collapse threshold
IBM_MAX_NODES      = 300    # pad size for diffusion / encoder

# ── Elliptic dataset settings ─────────────────────────────────────────────────
# The adapter auto-detects the path; override ELLIPTIC_DATA_DIR if needed.
ELLIPTIC_DATA_DIR  = None   # None = auto-detect from data/elliptic_bitcoin_dataset
ELLIPTIC_MAX_NODES = 100    # ego subgraph cap
ELLIPTIC_DEPTH     = 4      # BFS hop depth around each anchor transaction

# ── Diffusion hyperparameters (IBM) ───────────────────────────────────────────
DIFF_IBM_EPOCHS      = 300
DIFF_IBM_BATCH       = 32
DIFF_IBM_LR          = 2e-4
DIFF_IBM_WARMUP      = 15
DIFF_IBM_HIDDEN      = 128
DIFF_IBM_TIMESTEPS   = 500
DIFF_IBM_ADJ_W       = 0.3
DIFF_IBM_DENSITY_W   = 8.0   # was 3.0 — raised to dominate connectivity pressure
DIFF_IBM_LAUND_W     = 2.0
DIFF_IBM_GRAD_CLIP   = 1.0
DIFF_IBM_LAYERS      = 3     # was 4 — fewer layers → less oversmoothing on dense adj input
DIFF_IBM_EDGE_DROP   = 0.15  # fraction of adj_t edges zeroed before each forward pass

# ── Diffusion hyperparameters (Elliptic) ──────────────────────────────────────
DIFF_ELL_EPOCHS      = 150   # reduced from 200 — fits 9-hour SLURM budget
DIFF_ELL_BATCH       = 32
DIFF_ELL_LR          = 2e-4
DIFF_ELL_WARMUP      = 10
DIFF_ELL_HIDDEN      = 128
DIFF_ELL_TIMESTEPS   = 500
DIFF_ELL_ADJ_W       = 0.3
DIFF_ELL_DENSITY_W   = 8.0   # was 3.0
DIFF_ELL_LAUND_W     = 2.0
DIFF_ELL_GRAD_CLIP   = 1.0
DIFF_ELL_LAYERS      = 3     # was 4
DIFF_ELL_EDGE_DROP   = 0.15

# ── SimCLR hyperparameters (IBM) ──────────────────────────────────────────────
SIMCLR_IBM_EPOCHS      = 100
SIMCLR_IBM_BATCH       = 128
SIMCLR_IBM_LR          = 1e-3
SIMCLR_IBM_SUPCON_W    = 0.5
SIMCLR_IBM_SUPCON_T    = 0.07
SIMCLR_IBM_CKPT_EVERY  = 10
SIMCLR_IBM_P_DIFFUSION = 0.3   # fraction of views generated by diffusion
SIMCLR_IBM_T_FRAC      = 0.3   # noise level fraction for diffusion views

# ── SimCLR hyperparameters (Elliptic) ─────────────────────────────────────────
SIMCLR_ELL_EPOCHS      = 80    # reduced from 100 — fits 9-hour SLURM budget
SIMCLR_ELL_BATCH       = 128
SIMCLR_ELL_LR          = 1e-3
SIMCLR_ELL_SUPCON_W    = 0.5
SIMCLR_ELL_SUPCON_T    = 0.07
SIMCLR_ELL_CKPT_EVERY  = 10
SIMCLR_ELL_P_EDGE_DROP = 0.20
SIMCLR_ELL_P_FEAT_MASK = 0.15
SIMCLR_ELL_P_DIFFUSION = 0.30

# ── Option 1: class-conditional diffusion (IBM) ───────────────────────────────
# Train diffusion model conditioned on the graph's class label.
# Label dropout (CFG style) keeps unconditional generation possible.
DIFF_IBM_CLASS_COND  = True
DIFF_IBM_LABEL_DROP  = 0.10   # fraction of labels replaced with the null token

# ── Option 1: class-conditional diffusion (Elliptic) ─────────────────────────
DIFF_ELL_CLASS_COND  = True
DIFF_ELL_LABEL_DROP  = 0.10

# ── Option 2: online probe loss weight ────────────────────────────────────────
# Jointly-trained shallow head that makes the encoder directly classifiable.
SIMCLR_IBM_PROBE_W   = 0.20
SIMCLR_ELL_PROBE_W   = 0.20

# ── NT-Xent temperature ───────────────────────────────────────────────────────
# Lower temperature → harder negatives → sharper loss gradients → better
# separation.  Default was 0.5; 0.15 is a well-validated setting for SimCLR.
SIMCLR_IBM_NTXENT_T  = 0.15
SIMCLR_ELL_NTXENT_T  = 0.15

# ── Connectivity penalty in diffusion (IBM + Elliptic) ───────────────────────
# Penalises any real node whose predicted soft-degree is below 1, directly
# discouraging the model from generating graphs with isolated sub-components.
DIFF_IBM_CONN_W      = 0.50   # was 1.50 — high weight was pushing all nodes to over-connect
DIFF_ELL_CONN_W      = 0.50   # was 1.50

# ── Option 3: SimCLR alignment loss in diffusion (IBM) ───────────────────────
# Uses a frozen SimCLR encoder to align diffusion's predicted x0 with real
# graph embeddings.  Only active when a SimCLR checkpoint already exists
# (i.e. on a second training pass or fine-tune run).
DIFF_IBM_ALIGN_W     = 0.10
DIFF_IBM_ALIGN_EVERY = 5      # apply alignment every N batches to save compute

# ── Option 3: SimCLR alignment loss in diffusion (Elliptic) ──────────────────
DIFF_ELL_ALIGN_W     = 0.10
DIFF_ELL_ALIGN_EVERY = 5

# ── Ethereum Phishing Transaction Network settings ────────────────────────────
# The adapter auto-detects the pkl path; override ETHEREUM_PKL_PATH if needed.
ETHEREUM_PKL_PATH  = None   # None = auto-detect from data/Ethereum Phishing .../MulDiGraph.pkl
ETHEREUM_MAX_NODES = 100    # ego subgraph cap (same as Elliptic)
ETHEREUM_DEPTH     = 2      # BFS hop depth (smaller than Elliptic — graph is denser)

# ── Diffusion hyperparameters (Ethereum) ──────────────────────────────────────
DIFF_ETH_EPOCHS      = 150
DIFF_ETH_BATCH       = 32
DIFF_ETH_LR          = 2e-4
DIFF_ETH_WARMUP      = 10
DIFF_ETH_HIDDEN      = 128
DIFF_ETH_TIMESTEPS   = 500
DIFF_ETH_ADJ_W       = 0.3
DIFF_ETH_DENSITY_W   = 8.0
DIFF_ETH_LAUND_W     = 2.0
DIFF_ETH_GRAD_CLIP   = 1.0
DIFF_ETH_LAYERS      = 3
DIFF_ETH_EDGE_DROP   = 0.15
DIFF_ETH_CLASS_COND  = True
DIFF_ETH_LABEL_DROP  = 0.10
DIFF_ETH_CONN_W      = 0.50
DIFF_ETH_ALIGN_W     = 0.10
DIFF_ETH_ALIGN_EVERY = 5

# ── SimCLR hyperparameters (Ethereum) ─────────────────────────────────────────
SIMCLR_ETH_EPOCHS      = 80
SIMCLR_ETH_BATCH       = 64    # smaller than Elliptic — fewer training graphs
SIMCLR_ETH_LR          = 1e-3
SIMCLR_ETH_SUPCON_W    = 0.5
SIMCLR_ETH_SUPCON_T    = 0.07
SIMCLR_ETH_CKPT_EVERY  = 10
SIMCLR_ETH_P_EDGE_DROP = 0.20
SIMCLR_ETH_P_FEAT_MASK = 0.15
SIMCLR_ETH_P_DIFFUSION = 0.30
SIMCLR_ETH_PROBE_W     = 0.20
SIMCLR_ETH_NTXENT_T    = 0.15

# ══════════════════════════════════════════════════════════════════════════════
#  Internals — do not edit below this line
# ══════════════════════════════════════════════════════════════════════════════

import argparse
import math
import os
import random
import sys
import time
from pathlib import Path
from torch.utils.data import Dataset, DataLoader

import torch
import torch.nn.functional as F

ROOT_DIR   = Path(__file__).resolve().parent   # igraph_version/
DIFF_DIR   = ROOT_DIR / "diffusion"
SIMCLR_DIR = ROOT_DIR / "simclr"
DATA_DIR   = ROOT_DIR / "data"
CKPT_DIR   = ROOT_DIR / "checkpoints"

# Per-dataset checkpoint dirs — overridden by --ckpt-dir at runtime
IBM_DIFF_CKPT_DIR   = CKPT_DIR / "diffusion_ibm"
IBM_SIMCLR_CKPT_DIR = CKPT_DIR / "simclr_ibm"

for _p in (str(ROOT_DIR), str(DIFF_DIR), str(SIMCLR_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

# ─────────────────────────────────────────────────────────────────────────────
# IBM — diffusion training
# ─────────────────────────────────────────────────────────────────────────────

def train_diffusion_ibm(device):
    from diffusion.collate   import collate_fn
    from diffusion.dataset   import CachedDataset
    from diffusion.diff_util import create_diffusion, preprocess
    from diffusion.model     import DiffusionGNN
    from diffusion.resample  import LossSecondMomentResampler
    from diffusion.visualizations import run_all_visualizations
    from augmentation        import build_igraph_from_transactions
    from util import (preprocess_df, extract_networks_igraph)

    csv_stem   = Path(IBM_CSV_PATH).stem
    cache_path = DATA_DIR / f"cached_dataset_{csv_stem}.pt"
    graphs_dir = str(DIFF_DIR / "graphs")
    out_path   = IBM_DIFF_CKPT_DIR / "model.pt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"IBM Diffusion Training   ({DIFF_IBM_EPOCHS} epochs)")
    print(f"  CSV  : {IBM_CSV_PATH}")
    print(f"  Save : {out_path}")
    print('='*60)

    NODE_DIM = 19  # laundering flag (1) + topology (5) + transaction (5) + AML patterns (8)

    def _needs_rebuild():
        if not cache_path.exists():
            return True
        s = torch.load(str(cache_path), weights_only=False)
        if len(s) == 0 or s[0][0].shape[1] != NODE_DIM:
            cache_path.unlink()
            return True
        return False

    simclr_cache = DATA_DIR / f"simclr_networks_cache_{csv_stem}.pt"

    if _needs_rebuild():
        print("Extracting IBM networks …")
        df_full  = preprocess_df(IBM_CSV_PATH)
        networks = extract_networks_igraph(
            df_full, max_depth=IBM_MAX_DEPTH,
            max_networks=IBM_MAX_NETWORKS * 2,
            collapse_threshold=IBM_COLLAPSE_THRESH,
            max_nodes=IBM_MAX_NODES,
        )
        for net in networks:
            net["graph"] = build_igraph_from_transactions(net["transactions"])
        print(f"  {len(networks)} networks extracted. Preprocessing …")

        # Cache raw networks for SimCLR training so it skips re-extraction
        if not simclr_cache.exists():
            torch.save(networks, str(simclr_cache))
            print(f"  Saved raw network cache → {simclr_cache}")

        preprocess(networks, save_path=str(cache_path))

    print(f"Loading cache: {cache_path}")
    dataset  = CachedDataset(str(cache_path))
    loader   = DataLoader(dataset, batch_size=DIFF_IBM_BATCH,
                          shuffle=True, collate_fn=collate_fn, drop_last=True)
    all_x    = torch.cat([x for x, _adj in dataset], dim=0)
    x_mean   = torch.zeros(NODE_DIM); x_std = torch.ones(NODE_DIM)
    x_mean[1:] = all_x[:, 1:].mean(0); x_std[1:] = all_x[:, 1:].std(0).clamp(min=1e-6)
    x_mean, x_std = x_mean.to(device), x_std.to(device)
    print(f"Dataset: {len(dataset)} graphs")

    model     = DiffusionGNN(node_dim=NODE_DIM, hidden_dim=DIFF_IBM_HIDDEN,
                             num_layers=DIFF_IBM_LAYERS,
                             class_conditional=DIFF_IBM_CLASS_COND,
                             degree_conditioning=True).to(device)
    diffusion = create_diffusion(T=DIFF_IBM_TIMESTEPS)
    resampler = LossSecondMomentResampler(diffusion)
    optimizer = torch.optim.Adam(model.parameters(), lr=DIFF_IBM_LR)

    # Option 3: load frozen SimCLR encoder for embedding-space alignment loss.
    # Only activated when a SimCLR checkpoint from a previous run already exists.
    frozen_enc_ibm = None
    simclr_ckpt_ibm = IBM_SIMCLR_CKPT_DIR / "best_model.pt"
    if DIFF_IBM_ALIGN_W > 0 and simclr_ckpt_ibm.exists():
        from simclr import GraphEncoder
        from torch_geometric.data import Data as _PygData, Batch as _PygBatch
        _sc = torch.load(str(simclr_ckpt_ibm), map_location=device, weights_only=False)
        _sd = _sc["encoder_state_dict"]
        from simclr import encoder_dims_from_state_dict as _edfs
        _in, _hid, _nl, _bn, _gin = _edfs(_sd)
        frozen_enc_ibm = GraphEncoder(in_dim=_in, hidden_dim=_hid, out_dim=128,
                                       n_layers=_nl, use_bn=_bn, use_gin=_gin).to(device)
        frozen_enc_ibm.load_state_dict(_sc["encoder_state_dict"])
        frozen_enc_ibm.eval()
        for _p in frozen_enc_ibm.parameters():
            _p.requires_grad_(False)
        print(f"  [Option 3] Alignment loss enabled (w={DIFF_IBM_ALIGN_W}) — "
              f"SimCLR ckpt loaded from {simclr_ckpt_ibm.name}")
    else:
        from torch_geometric.data import Data as _PygData, Batch as _PygBatch

    def _lr(ep):
        if ep < DIFF_IBM_WARMUP:
            return (ep + 1) / DIFF_IBM_WARMUP
        p = (ep - DIFF_IBM_WARMUP) / max(1, DIFF_IBM_EPOCHS - DIFF_IBM_WARMUP)
        return 0.5 * (1.0 + math.cos(math.pi * p))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, _lr)
    use_amp   = (str(device) == "cuda")
    scaler    = torch.amp.GradScaler("cuda", enabled=use_amp)
    t0        = time.time()

    for epoch in range(DIFF_IBM_EPOCHS):
        model.train()
        total = 0.0; nb = 0

        for x_batch, adj_batch, mask in loader:
            x_batch   = x_batch.to(device)
            adj_batch = adj_batch.to(device)
            mask      = mask.to(device)
            n_nodes   = x_batch.shape[1]
            nb       += 1

            x_norm = x_batch.clone()
            x_norm[:, :, 1:] = (x_batch[:, :, 1:] - x_mean[1:]) / x_std[1:]
            x_norm = x_norm * mask.unsqueeze(-1)

            # Option 1: extract per-graph class labels from col-0 laundering flag
            if DIFF_IBM_CLASS_COND:
                graph_labels = ((x_batch[:, :, 0] * mask).sum(dim=1) > 0).long()
                null_mask    = torch.rand(graph_labels.shape[0], device=device) < DIFF_IBM_LABEL_DROP
                class_labels = graph_labels.masked_fill(null_mask, 2)   # 2 = CFG null token
            else:
                class_labels = None

            t, weights = resampler.sample(x_batch.shape[0], device)
            with torch.autocast("cuda", enabled=use_amp):
                x_t, adj_t = diffusion.q_sample(x_norm, t, node_mask=mask, adj_start=adj_batch)
                # Edge dropout: randomly zero some edges in the input adjacency so the
                # model cannot rely on a dense adj at every step.  This reduces
                # oversmoothing (all embeddings collapse → uniform adj_pred) and teaches
                # the model to predict reasonable adjacency even from sparser inputs.
                if DIFF_IBM_EDGE_DROP > 0:
                    drop = torch.bernoulli(
                        torch.full_like(adj_t, 1.0 - DIFF_IBM_EDGE_DROP)
                    )
                    adj_t_in = adj_t * drop
                else:
                    adj_t_in = adj_t
                eps_pred, adj_pred, node_pred = model(
                    x_t, diffusion._scale_timesteps(t),
                    adj=adj_t_in, node_mask=mask,
                    class_labels=class_labels,        # Option 1
                )
                # noise-pred loss on continuous features
                noise_true = x_t[:, :, 1:] - x_norm[:, :, 1:]
                mse = ((eps_pred[:, :, 1:] - noise_true) ** 2 * mask.unsqueeze(-1)).sum() / mask.sum().clamp(1)

            # BCE losses computed in float32 — bce is unsafe inside autocast
            eps_pred_f = eps_pred.float()
            adj_pred_f = adj_pred.float()
            mask_f     = mask.float()
            bce  = F.binary_cross_entropy(
                eps_pred_f[:, :, 0].clamp(1e-6, 1-1e-6) * mask_f,
                x_batch[:, :, 0].float() * mask_f, reduction="sum"
            ) / mask_f.sum().clamp(1)
            _m2 = mask_f[:, :, None] * mask_f[:, None, :]
            adj_l = F.binary_cross_entropy(
                adj_pred_f.clamp(1e-6, 1-1e-6) * _m2,
                adj_batch.float() * _m2, reduction="sum"
            ) / (_m2.sum()).clamp(1)
            pred_dens = adj_pred_f.sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            true_dens = adj_batch.float().sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            dens_loss = ((pred_dens - true_dens) ** 2).mean()

            # Connectivity penalty: every real node must have soft degree >= 1.
            # _m2 masks padding; sum over the last dim gives per-node soft degree.
            soft_deg  = (adj_pred_f * _m2).sum(dim=-1)           # [B, N]
            conn_loss = (F.relu(1.0 - soft_deg) * mask_f).sum() / mask_f.sum().clamp(1)

            # Option 3: embedding-space alignment — diffusion's predicted x0 should
            # land near the real graph in SimCLR embedding space.  Gradients flow
            # through eps_pred → model params; the frozen encoder contributes no
            # parameter updates.
            align_loss = torch.tensor(0.0, device=device)
            if frozen_enc_ibm is not None and nb % DIFF_IBM_ALIGN_EVERY == 0:
                ab_t_v  = torch.tensor(
                    [float(diffusion.alphas_cumprod[int(ti.item())]) for ti in t],
                    dtype=torch.float32, device=device,
                )
                sqrt_ab = ab_t_v.sqrt().view(-1, 1, 1).clamp(min=1e-8)
                sqrt_1m = (1.0 - ab_t_v).sqrt().view(-1, 1, 1)
                # Reconstruct x0_pred from eps_pred; grad flows through eps_pred_f
                x0_cont = (x_t[..., 1:].float().detach() - sqrt_1m * eps_pred_f[..., 1:]) / sqrt_ab
                x0_cont = x0_cont * x_std[1:] + x_mean[1:]      # denormalise
                pyg_pred_list, pyg_real_list = [], []
                _enc_in = frozen_enc_ibm.in_dim
                for bi in range(x_batch.shape[0]):
                    n_bi = int(mask[bi].sum().item())
                    if n_bi < 2:
                        continue
                    ei_pred = (adj_pred_f[bi, :n_bi, :n_bi].detach() > 0.5).nonzero(as_tuple=False).T.contiguous()
                    ei_real = (adj_batch[bi, :n_bi, :n_bi] > 0.5).nonzero(as_tuple=False).T.contiguous()
                    pyg_pred_list.append(_PygData(x=x0_cont[bi, :n_bi, :_enc_in], edge_index=ei_pred))
                    pyg_real_list.append(_PygData(x=x_batch[bi, :n_bi, 1:1+_enc_in].detach(), edge_index=ei_real))
                if pyg_pred_list:
                    bp = _PygBatch.from_data_list(pyg_pred_list)
                    br = _PygBatch.from_data_list(pyg_real_list)
                    h_pred = F.normalize(frozen_enc_ibm(bp), dim=-1)
                    with torch.no_grad():
                        h_real = F.normalize(frozen_enc_ibm(br), dim=-1)
                    align_loss = (1.0 - (h_pred * h_real.detach()).sum(dim=-1)).mean()

            loss = (mse + DIFF_IBM_LAUND_W   * bce
                    + DIFF_IBM_ADJ_W     * adj_l
                    + DIFF_IBM_DENSITY_W * dens_loss
                    + DIFF_IBM_CONN_W    * conn_loss
                    + DIFF_IBM_ALIGN_W   * align_loss)

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), DIFF_IBM_GRAD_CLIP)
            scaler.step(optimizer); scaler.update()
            total += loss.item()

        scheduler.step()
        if (epoch + 1) % 10 == 0 or epoch < 3:
            print(f"Epoch {epoch+1:4d}/{DIFF_IBM_EPOCHS} | "
                  f"loss={total/max(nb,1):.4f} | lr={scheduler.get_last_lr()[0]:.2e} | "
                  f"{time.time()-t0:.0f}s")

        torch.save({"model": model.state_dict(),
                    "x_mean": x_mean.cpu(), "x_std": x_std.cpu(),
                    "class_conditional": DIFF_IBM_CLASS_COND,
                    "num_layers": DIFF_IBM_LAYERS,
                    "degree_conditioning": True}, out_path)

    print(f"\nIBM diffusion checkpoint saved → {out_path}")


# ─────────────────────────────────────────────────────────────────────────────
# IBM — SimCLR training
# ─────────────────────────────────────────────────────────────────────────────

def train_simclr_ibm(device):
    from simclr import GraphEncoder, ProjectionHead, train_simclr_fast
    from augmentation import build_igraph_from_transactions
    from util import (preprocess_df, extract_networks_igraph)
    from diffusion.model     import DiffusionGNN
    from diffusion.diff_util import create_diffusion

    ckpt_dir  = IBM_SIMCLR_CKPT_DIR
    diff_ckpt = IBM_DIFF_CKPT_DIR / "model.pt"
    csv_stem  = Path(IBM_CSV_PATH).stem
    cache_pt  = DATA_DIR / f"simclr_networks_cache_{csv_stem}.pt"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"IBM SimCLR Training   ({SIMCLR_IBM_EPOCHS} epochs)")
    print(f"  CSV  : {IBM_CSV_PATH}")
    print(f"  Save : {ckpt_dir}")
    print('='*60)

    def _cache_stale(nets):
        """Return True if the cached networks have the wrong node feature dim."""
        for n in nets:
            xd = n.get("x_dense")
            if xd is not None:
                return xd.shape[1] != 19
        return False  # no x_dense yet — will be built on first use

    networks = None
    if cache_pt.exists():
        print(f"Loading networks from cache: {cache_pt}")
        networks = torch.load(str(cache_pt), weights_only=False)
        if _cache_stale(networks):
            print("  Stale cache (wrong node_dim) — rebuilding …")
            cache_pt.unlink()
            networks = None

    if networks is None:
        print("Extracting IBM networks …")
        df_full  = preprocess_df(IBM_CSV_PATH)
        networks = extract_networks_igraph(
            df_full, max_depth=IBM_MAX_DEPTH,
            max_networks=IBM_MAX_NETWORKS * 2,
            collapse_threshold=IBM_COLLAPSE_THRESH,
            max_nodes=IBM_MAX_NODES,
        )
        for net in networks:
            net["graph"] = build_igraph_from_transactions(net["transactions"])
        torch.save(networks, str(cache_pt))
        print(f"Saved cache → {cache_pt}")
    print(f"  {len(networks)} networks loaded")

    # Load optional diffusion model for augmentation
    diff_model = diffusion = x_mean = x_std = None
    if diff_ckpt.exists():
        ckpt            = torch.load(str(diff_ckpt), map_location=device, weights_only=False)
        node_dim_ckpt   = ckpt["model"]["input_proj.weight"].shape[1]
        class_cond_ckpt = ckpt.get("class_conditional", False)
        num_layers_ckpt = ckpt.get("num_layers", 4)   # fallback for old checkpoints
        deg_cond_ckpt   = ckpt.get("degree_conditioning",
                                    "degree_proj.weight" in ckpt["model"])
        diff_model = DiffusionGNN(node_dim=node_dim_ckpt, hidden_dim=DIFF_IBM_HIDDEN,
                                  num_layers=num_layers_ckpt,
                                  class_conditional=class_cond_ckpt,
                                  degree_conditioning=deg_cond_ckpt).to(device)
        diff_model.load_state_dict(ckpt["model"])
        diff_model.eval()
        diffusion = create_diffusion(T=DIFF_IBM_TIMESTEPS)
        x_mean    = ckpt["x_mean"].to(device)
        x_std     = ckpt["x_std"].to(device)
        print(f"  Diffusion augmentation enabled (node_dim={node_dim_ckpt}, "
              f"class_conditional={class_cond_ckpt}).")
    else:
        node_dim_ckpt = 11  # full feature dim; encoder will use node_dim_ckpt - 1
        print(f"  Diffusion checkpoint not found at {diff_ckpt} — training without augmentation.")

    # node_dim_ckpt is the diffusion model's full feature dim (includes col 0 = laundering flag).
    # The encoder receives col 0 stripped, so in_dim = node_dim_ckpt - 1.
    encoder   = GraphEncoder(in_dim=node_dim_ckpt - 1, hidden_dim=128, out_dim=128,
                             n_layers=3, use_bn=True).to(device)
    projector = ProjectionHead(in_dim=128, proj_dim=64).to(device)
    optimizer = torch.optim.Adam(
        list(encoder.parameters()) + list(projector.parameters()), lr=SIMCLR_IBM_LR
    )

    # Precompute full 19-dim x_dense for every network once before training so that
    # the inner loop's cache-miss branch (which calls compute_pattern_features) is
    # never hit during training — only the fast cache-hit path runs per batch.
    print("  Precomputing node features (19-dim) …")
    from diffusion.diff_util import network_to_dense as _ntd_pre
    for _net in networks:
        _xd = _net.get("x_dense")
        if _xd is None or _xd.shape[1] != 19:
            _x, _ = _ntd_pre(_net)
            _net["x_dense"] = _x
    print(f"  Precomputation done ({len(networks)} networks).")

    train_simclr_fast(
        networks=networks, full_df=None,
        encoder=encoder, projector=projector, optimizer=optimizer,
        device=device,
        batch_size=SIMCLR_IBM_BATCH,
        epochs=SIMCLR_IBM_EPOCHS,
        checkpoint_dir=str(ckpt_dir),
        diffusion_model=diff_model, diffusion=diffusion,
        x_mean=x_mean, x_std=x_std,
        p_diffusion=SIMCLR_IBM_P_DIFFUSION,
        diffusion_t_frac=SIMCLR_IBM_T_FRAC,
        max_nodes=IBM_MAX_NODES,
        probe_weight=SIMCLR_IBM_PROBE_W,
        ntxent_temperature=SIMCLR_IBM_NTXENT_T,
        supcon_weight=SIMCLR_IBM_SUPCON_W,
        supcon_temperature=SIMCLR_IBM_SUPCON_T,
        # Task-aware augmentation
        use_curriculum=True,
        curriculum_epochs=max(1, SIMCLR_IBM_EPOCHS // 2),
        use_motif_preserving=True,
        use_saliency=SIMCLR_IBM_PROBE_W > 0,
        saliency_update_interval=20,
        # Start with multi-step DDIM views so the encoder warms up before the
        # probe is fit; switch to guided views after probe_warmup_epochs.
        view_type="multistep_to_guided" if (diff_model is not None and SIMCLR_IBM_PROBE_W > 0) else "single_step",
        diff_n_steps=5,
        diff_t_start_frac=0.4,
        diff_guidance_scale=1.5,
        probe_warmup_epochs=max(20, SIMCLR_IBM_EPOCHS // 3),
    )
    print(f"\nIBM SimCLR checkpoints saved → {ckpt_dir}")


# ─────────────────────────────────────────────────────────────────────────────
# Elliptic — diffusion training
# ─────────────────────────────────────────────────────────────────────────────

def train_diffusion_elliptic(device):
    from diffusion.collate   import collate_fn
    from diffusion.diff_util import create_diffusion
    from diffusion.model     import DiffusionGNN
    from diffusion.resample  import LossSecondMomentResampler
    from data.elliptic_adapter import load_elliptic_pyg_graphs

    cache_path = DATA_DIR / "elliptic_diffusion_cache_d4.pt"
    out_path   = CKPT_DIR / "diffusion_elliptic" / "model.pt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"Elliptic Diffusion Training   ({DIFF_ELL_EPOCHS} epochs)")
    print(f"  max_nodes={ELLIPTIC_MAX_NODES}  depth={ELLIPTIC_DEPTH}")
    print(f"  Save : {out_path}")
    print('='*60)

    NODE_DIM = 6

    def _pyg_to_dense(data):
        n = data.x.shape[0]
        x = torch.zeros(n, NODE_DIM)
        x[:, 0] = float(data.y.item())
        x[:, 1:] = data.x
        adj = torch.zeros(n, n)
        ei = data.edge_index
        if ei.shape[1] > 0:
            valid = ei[0] != ei[1]
            src, dst = ei[0][valid], ei[1][valid]
            inb = (src < n) & (dst < n)
            adj[src[inb], dst[inb]] = 1.0
        return x, adj

    if not cache_path.exists():
        kwargs = dict(max_nodes=ELLIPTIC_MAX_NODES, depth=ELLIPTIC_DEPTH)
        if ELLIPTIC_DATA_DIR:
            kwargs["data_dir"] = ELLIPTIC_DATA_DIR
        raw = load_elliptic_pyg_graphs(**kwargs)
        pairs = [(x, a) for g in raw for x, a in [_pyg_to_dense(g)] if g.x.shape[0] >= 3]
        torch.save(pairs, str(cache_path))
        print(f"Saved {len(pairs)} dense pairs → {cache_path}")
    else:
        pairs = torch.load(str(cache_path), weights_only=False)
        if len(pairs) == 0 or pairs[0][0].shape[1] != NODE_DIM:
            cache_path.unlink()
            return train_diffusion_elliptic(device)

    pairs = [(x, a) for x, a in pairs if x.shape[0] <= ELLIPTIC_MAX_NODES]
    print(f"Dataset: {len(pairs)} graphs")

    class _DS(Dataset):
        def __getitem__(self, i): return pairs[i]
        def __len__(self): return len(pairs)

    loader   = DataLoader(_DS(), batch_size=DIFF_ELL_BATCH,
                          shuffle=True, collate_fn=collate_fn, drop_last=True)
    all_x    = torch.cat([x for x, _ in pairs], dim=0)
    x_mean   = torch.zeros(NODE_DIM); x_std = torch.ones(NODE_DIM)
    x_mean[1:] = all_x[:, 1:].mean(0); x_std[1:] = all_x[:, 1:].std(0).clamp(min=1e-6)
    x_mean, x_std = x_mean.to(device), x_std.to(device)

    model     = DiffusionGNN(node_dim=NODE_DIM, hidden_dim=DIFF_ELL_HIDDEN,
                             num_layers=DIFF_ELL_LAYERS,
                             class_conditional=DIFF_ELL_CLASS_COND,
                             degree_conditioning=True).to(device)
    diffusion = create_diffusion(T=DIFF_ELL_TIMESTEPS)
    resampler = LossSecondMomentResampler(diffusion)
    optimizer = torch.optim.Adam(model.parameters(), lr=DIFF_ELL_LR)

    # Option 3: frozen SimCLR encoder for alignment loss (active on second pass)
    frozen_enc_ell = None
    simclr_ckpt_ell = CKPT_DIR / "simclr_elliptic" / "best_model.pt"
    if DIFF_ELL_ALIGN_W > 0 and simclr_ckpt_ell.exists():
        from simclr import GraphEncoder
        from torch_geometric.data import Data as _PygData, Batch as _PygBatch
        _sc = torch.load(str(simclr_ckpt_ell), map_location=device, weights_only=False)
        _sd = _sc["encoder_state_dict"]
        from simclr import encoder_dims_from_state_dict as _edfs_ell
        _in, _hid, _nl, _bn, _gin = _edfs_ell(_sd)
        frozen_enc_ell = GraphEncoder(in_dim=_in, hidden_dim=_hid, out_dim=128,
                                       n_layers=_nl, use_bn=_bn, use_gin=_gin).to(device)
        frozen_enc_ell.load_state_dict(_sc["encoder_state_dict"])
        frozen_enc_ell.eval()
        for _p in frozen_enc_ell.parameters():
            _p.requires_grad_(False)
        print(f"  [Option 3] Alignment loss enabled (w={DIFF_ELL_ALIGN_W}) — "
              f"SimCLR ckpt loaded from {simclr_ckpt_ell.name}")
    else:
        from torch_geometric.data import Data as _PygData, Batch as _PygBatch

    def _lr(ep):
        if ep < DIFF_ELL_WARMUP:
            return (ep + 1) / DIFF_ELL_WARMUP
        p = (ep - DIFF_ELL_WARMUP) / max(1, DIFF_ELL_EPOCHS - DIFF_ELL_WARMUP)
        return 0.5 * (1.0 + math.cos(math.pi * p))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, _lr)
    use_amp   = (str(device) == "cuda")
    scaler    = torch.amp.GradScaler("cuda", enabled=use_amp)
    t0        = time.time()

    for epoch in range(DIFF_ELL_EPOCHS):
        model.train()
        total = 0.0; nb = 0

        for x_batch, adj_batch, mask in loader:
            x_batch   = x_batch.to(device)
            adj_batch = adj_batch.to(device)
            mask      = mask.to(device)
            n_nodes   = x_batch.shape[1]
            nb       += 1

            x_norm = x_batch.clone()
            x_norm[:, :, 1:] = (x_batch[:, :, 1:] - x_mean[1:]) / x_std[1:]
            x_norm = x_norm * mask.unsqueeze(-1)

            # Option 1: per-graph class labels with CFG dropout
            if DIFF_ELL_CLASS_COND:
                graph_labels = ((x_batch[:, :, 0] * mask).sum(dim=1) > 0).long()
                null_mask    = torch.rand(graph_labels.shape[0], device=device) < DIFF_ELL_LABEL_DROP
                class_labels = graph_labels.masked_fill(null_mask, 2)
            else:
                class_labels = None

            t, _ = resampler.sample(x_batch.shape[0], device)
            with torch.autocast("cuda", enabled=use_amp):
                x_t, adj_t = diffusion.q_sample(x_norm, t, node_mask=mask, adj_start=adj_batch)
                if DIFF_ELL_EDGE_DROP > 0:
                    drop = torch.bernoulli(
                        torch.full_like(adj_t, 1.0 - DIFF_ELL_EDGE_DROP)
                    )
                    adj_t_in = adj_t * drop
                else:
                    adj_t_in = adj_t
                eps_pred, adj_pred, _ = model(
                    x_t, diffusion._scale_timesteps(t),
                    adj=adj_t_in, node_mask=mask,
                    class_labels=class_labels,        # Option 1
                )
                noise_true = x_t[:, :, 1:] - x_norm[:, :, 1:]
                mse = ((eps_pred[:, :, 1:] - noise_true) ** 2 * mask.unsqueeze(-1)).sum() / mask.sum().clamp(1)

            # BCE losses computed in float32 — bce is unsafe inside autocast
            eps_pred_f = eps_pred.float()
            adj_pred_f = adj_pred.float()
            mask_f     = mask.float()
            bce  = F.binary_cross_entropy(
                eps_pred_f[:, :, 0].clamp(1e-6, 1-1e-6) * mask_f,
                x_batch[:, :, 0].float() * mask_f, reduction="sum"
            ) / mask_f.sum().clamp(1)
            _m2 = mask_f[:, :, None] * mask_f[:, None, :]
            adj_l = F.binary_cross_entropy(
                adj_pred_f.clamp(1e-6, 1-1e-6) * _m2,
                adj_batch.float() * _m2, reduction="sum"
            ) / (_m2.sum()).clamp(1)
            pred_dens = adj_pred_f.sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            true_dens = adj_batch.float().sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            dens_loss = ((pred_dens - true_dens) ** 2).mean()

            # Connectivity penalty: penalise isolated nodes in the predicted adjacency
            soft_deg  = (adj_pred_f * _m2).sum(dim=-1)
            conn_loss = (F.relu(1.0 - soft_deg) * mask_f).sum() / mask_f.sum().clamp(1)

            # Option 3: embedding-space alignment
            align_loss = torch.tensor(0.0, device=device)
            if frozen_enc_ell is not None and nb % DIFF_ELL_ALIGN_EVERY == 0:
                ab_t_v  = torch.tensor(
                    [float(diffusion.alphas_cumprod[int(ti.item())]) for ti in t],
                    dtype=torch.float32, device=device,
                )
                sqrt_ab = ab_t_v.sqrt().view(-1, 1, 1).clamp(min=1e-8)
                sqrt_1m = (1.0 - ab_t_v).sqrt().view(-1, 1, 1)
                x0_cont = (x_t[..., 1:].float().detach() - sqrt_1m * eps_pred_f[..., 1:]) / sqrt_ab
                x0_cont = x0_cont * x_std[1:] + x_mean[1:]
                pyg_pred_list, pyg_real_list = [], []
                for bi in range(x_batch.shape[0]):
                    n_bi = int(mask[bi].sum().item())
                    if n_bi < 2:
                        continue
                    ei_pred = (adj_pred_f[bi, :n_bi, :n_bi].detach() > 0.5).nonzero(as_tuple=False).T.contiguous()
                    ei_real = (adj_batch[bi, :n_bi, :n_bi] > 0.5).nonzero(as_tuple=False).T.contiguous()
                    pyg_pred_list.append(_PygData(x=x0_cont[bi, :n_bi], edge_index=ei_pred))
                    pyg_real_list.append(_PygData(x=x_batch[bi, :n_bi, 1:].detach(), edge_index=ei_real))
                if pyg_pred_list:
                    bp = _PygBatch.from_data_list(pyg_pred_list)
                    br = _PygBatch.from_data_list(pyg_real_list)
                    h_pred = F.normalize(frozen_enc_ell(bp), dim=-1)
                    with torch.no_grad():
                        h_real = F.normalize(frozen_enc_ell(br), dim=-1)
                    align_loss = (1.0 - (h_pred * h_real.detach()).sum(dim=-1)).mean()

            loss = (mse + DIFF_ELL_LAUND_W   * bce
                    + DIFF_ELL_ADJ_W     * adj_l
                    + DIFF_ELL_DENSITY_W * dens_loss
                    + DIFF_ELL_CONN_W    * conn_loss
                    + DIFF_ELL_ALIGN_W   * align_loss)

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), DIFF_ELL_GRAD_CLIP)
            scaler.step(optimizer); scaler.update()
            total += loss.item()

        scheduler.step()
        if (epoch + 1) % 10 == 0 or epoch < 3:
            print(f"Epoch {epoch+1:4d}/{DIFF_ELL_EPOCHS} | "
                  f"loss={total/max(nb,1):.4f} | {time.time()-t0:.0f}s")

        torch.save({"model": model.state_dict(),
                    "x_mean": x_mean.cpu(), "x_std": x_std.cpu(),
                    "class_conditional": DIFF_ELL_CLASS_COND,
                    "num_layers": DIFF_ELL_LAYERS,
                    "degree_conditioning": True}, out_path)

    print(f"\nElliptic diffusion checkpoint saved → {out_path}")


# ─────────────────────────────────────────────────────────────────────────────
# Elliptic — SimCLR training
# ─────────────────────────────────────────────────────────────────────────────

def train_simclr_elliptic(device):
    from simclr import GraphEncoder, ProjectionHead, OnlineProbeHead, nt_xent_loss, sup_con_loss, _is_connected_ei
    from torch_geometric.data import Data, Batch
    from diffusion.model     import DiffusionGNN
    from diffusion.diff_util import create_diffusion
    from data.elliptic_adapter import load_elliptic_pyg_graphs

    ckpt_dir  = CKPT_DIR / "simclr_elliptic"
    diff_ckpt = CKPT_DIR / "diffusion_elliptic" / "model.pt"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"Elliptic SimCLR Training   ({SIMCLR_ELL_EPOCHS} epochs)")
    print(f"  max_nodes={ELLIPTIC_MAX_NODES}  depth={ELLIPTIC_DEPTH}")
    print(f"  Save : {ckpt_dir}")
    print('='*60)

    # ── load data ──────────────────────────────────────────────────────────────
    kwargs = dict(max_nodes=ELLIPTIC_MAX_NODES, depth=ELLIPTIC_DEPTH)
    if ELLIPTIC_DATA_DIR:
        kwargs["data_dir"] = ELLIPTIC_DATA_DIR
    raw_graphs = load_elliptic_pyg_graphs(**kwargs)

    def _extend_6d(g):
        n = g.x.shape[0]
        lc = torch.full((n, 1), float(g.y.item()))
        x6 = torch.cat([lc, g.x], dim=1)
        return Data(x=x6, edge_index=g.edge_index.clone(), y=g.y.clone())

    graphs = [_extend_6d(g) for g in raw_graphs]
    n_ill  = sum(g.y.item() == 1 for g in graphs)
    print(f"  {len(graphs)} graphs ({n_ill} illicit, {len(graphs)-n_ill} licit)")

    # ── load optional diffusion model ──────────────────────────────────────────
    diff_model = diffusion = x_mean = x_std = None
    if diff_ckpt.exists():
        ckpt            = torch.load(str(diff_ckpt), map_location=device, weights_only=False)
        class_cond_ckpt = ckpt.get("class_conditional", False)
        num_layers_ckpt = ckpt.get("num_layers", 4)
        deg_cond_ckpt   = ckpt.get("degree_conditioning",
                                    "degree_proj.weight" in ckpt["model"])
        diff_model = DiffusionGNN(node_dim=6, hidden_dim=DIFF_ELL_HIDDEN,
                                  num_layers=num_layers_ckpt,
                                  class_conditional=class_cond_ckpt,
                                  degree_conditioning=deg_cond_ckpt).to(device)
        diff_model.load_state_dict(ckpt["model"])
        diff_model.eval()
        diffusion = create_diffusion(T=DIFF_ELL_TIMESTEPS)
        x_mean    = ckpt["x_mean"].to(device)
        x_std     = ckpt["x_std"].to(device)
        print(f"  Diffusion augmentation enabled (class_conditional={class_cond_ckpt}).")
    else:
        print(f"  Diffusion checkpoint not found at {diff_ckpt} — structural augmentation only.")

    # ── augmentations ──────────────────────────────────────────────────────────
    def _augment(g, p_edge=SIMCLR_ELL_P_EDGE_DROP, p_feat=SIMCLR_ELL_P_FEAT_MASK):
        x = g.x.clone()
        mask = torch.rand(x.shape[0], x.shape[1] - 1) > p_feat
        x[:, 1:] *= mask.float()
        ei = g.edge_index
        if ei.shape[1] > 0:
            n_edges  = ei.shape[1] // 2
            keep     = torch.rand(n_edges) > p_edge
            keep_idx = keep.repeat_interleave(2).nonzero(as_tuple=False).squeeze(1)
            if len(keep_idx) > 0:
                ei = ei[:, keep_idx]
            else:
                ei = torch.zeros(2, 0, dtype=torch.long)
        return Data(x=x, edge_index=ei, y=g.y.clone())

    def _diff_view(g):
        if diff_model is None:
            return None
        n = g.x.shape[0]
        x_pad  = torch.zeros(1, ELLIPTIC_MAX_NODES, 6, device=device)
        a_pad  = torch.zeros(1, ELLIPTIC_MAX_NODES, ELLIPTIC_MAX_NODES, device=device)
        msk    = torch.zeros(1, ELLIPTIC_MAX_NODES, device=device)
        x_pad[0, :n]     = g.x.to(device)
        msk[0, :n]       = 1.0
        ei = g.edge_index
        if ei.shape[1] > 0:
            valid = ei[0] != ei[1]
            s, d  = ei[0][valid], ei[1][valid]
            inb   = (s < n) & (d < n)
            a_pad[0, s[inb], d[inb]] = 1.0
        x_n = x_pad.clone()
        x_n[:, :, 1:] = (x_pad[:, :, 1:] - x_mean[1:]) / x_std[1:]
        x_n = x_n * msk.unsqueeze(-1)
        t_frac = random.uniform(0.1, 0.4)
        t_val  = max(1, int(t_frac * DIFF_ELL_TIMESTEPS))
        t      = torch.tensor([t_val], device=device)
        x_t, adj_t = diffusion.q_sample(x_n, t, node_mask=msk, adj_start=a_pad)
        try:
            with torch.no_grad():
                ep, ap, _ = diff_model(x_t, diffusion._scale_timesteps(t),
                                       adj=adj_t, node_mask=msk)
                x0_c = diffusion._predict_xstart_from_eps(x_t[..., 1:], t, ep[..., 1:])
                x0_b = ep[..., 0:1].clamp(0.0, 1.0)
            x0     = torch.cat([x0_b, x0_c], dim=-1)[0, :n].cpu()
            x0[:, 1:] = x0[:, 1:] * x_std[1:].cpu() + x_mean[1:].cpu()
            deg    = ap[0, :n, :n].cpu().sum(-1)
            x0[:, 1] = deg / deg.max().clamp(min=1.0)
            ei_out = (ap[0, :n, :n].cpu() > 0.5).nonzero(as_tuple=False).T.contiguous()
            return Data(x=x0, edge_index=ei_out, y=g.y.clone())
        except Exception:
            return None

    # ── training loop ──────────────────────────────────────────────────────────
    # in_dim=5: col 0 (laundering flag) stripped before encoder (label-leakage fix)
    encoder    = GraphEncoder(in_dim=5, hidden_dim=128, out_dim=128,
                              n_layers=3, use_bn=True).to(device)
    projector  = ProjectionHead(in_dim=128, proj_dim=64).to(device)
    ell_probe  = OnlineProbeHead(in_dim=128).to(device) if SIMCLR_ELL_PROBE_W > 0 else None
    all_params = (list(encoder.parameters()) + list(projector.parameters())
                  + (list(ell_probe.parameters()) if ell_probe else []))
    optimizer  = torch.optim.Adam(all_params, lr=SIMCLR_ELL_LR)

    best_loss = float("inf")
    t0        = time.time()

    for epoch in range(SIMCLR_ELL_EPOCHS):
        encoder.train(); projector.train()
        if ell_probe: ell_probe.train()
        if diff_model: diff_model.eval()
        random.shuffle(graphs)
        total = nx_t = sc_t = probe_t = 0.0; nb = 0

        for i in range(0, len(graphs), SIMCLR_ELL_BATCH):
            batch = graphs[i : i + SIMCLR_ELL_BATCH]
            v1, v2, lbls = [], [], []
            for g in batch:
                v1.append(_augment(g))
                if diff_model and random.random() < SIMCLR_ELL_P_DIFFUSION:
                    dv = _diff_view(g)
                    # Reject disconnected diffusion views → fall back to structural augmentation
                    if dv is not None and not _is_connected_ei(dv.edge_index, dv.x.shape[0]):
                        dv = None
                    v2.append(dv if dv is not None else _augment(g))
                else:
                    v2.append(_augment(g))
                lbls.append(int(g.y.item()))

            labels = torch.tensor(lbls, dtype=torch.long, device=device)
            b1 = Batch.from_data_list(v1).to(device)
            b2 = Batch.from_data_list(v2).to(device)

            optimizer.zero_grad()
            h1 = encoder(b1); h2 = encoder(b2)
            z1 = projector(h1); z2 = projector(h2)
            ntxent  = nt_xent_loss(z1, z2, temperature=SIMCLR_ELL_NTXENT_T)
            z_all   = torch.cat([z1, z2]); lbl_all = torch.cat([labels, labels])
            sc      = sup_con_loss(z_all, lbl_all, temperature=SIMCLR_ELL_SUPCON_T)

            # Option 2: online probe loss on encoder outputs (128-dim), not projector outputs
            if ell_probe is not None:
                h_all       = torch.cat([h1.float(), h2.float()], dim=0)
                probe_logit = ell_probe(F.normalize(h_all, dim=-1))
                probe_loss  = F.binary_cross_entropy_with_logits(probe_logit, lbl_all.float())
            else:
                probe_loss = torch.tensor(0.0, device=device)

            loss = ntxent + SIMCLR_ELL_SUPCON_W * sc + SIMCLR_ELL_PROBE_W * probe_loss
            loss.backward(); optimizer.step()

            total   += loss.item()
            nx_t    += ntxent.item()
            sc_t    += sc.item() if isinstance(sc, torch.Tensor) else float(sc)
            probe_t += probe_loss.item()
            nb      += 1

        avg        = total   / max(nb, 1)
        probe_str  = f", probe={probe_t/max(nb,1):.4f}" if ell_probe else ""
        print(f"Epoch {epoch+1:3d}/{SIMCLR_ELL_EPOCHS} | "
              f"loss={avg:.4f} (nt_xent={nx_t/max(nb,1):.4f}, supcon={sc_t/max(nb,1):.4f}{probe_str}) | "
              f"{time.time()-t0:.1f}s")

        _ckpt_data = {
            "encoder_state_dict":   encoder.state_dict(),
            "projector_state_dict": projector.state_dict(),
            "probe_state_dict":     ell_probe.state_dict() if ell_probe else None,
            "loss": avg, "epoch": epoch + 1,
        }
        if (epoch + 1) % SIMCLR_ELL_CKPT_EVERY == 0:
            torch.save(_ckpt_data, ckpt_dir / f"epoch_{epoch+1}.pt")

        if avg < best_loss:
            best_loss = avg
            torch.save(_ckpt_data, ckpt_dir / "best_model.pt")

    print(f"\nElliptic SimCLR checkpoints saved → {ckpt_dir}  (best loss={best_loss:.4f})")


# ─────────────────────────────────────────────────────────────────────────────
# Ethereum Phishing — diffusion training
# ─────────────────────────────────────────────────────────────────────────────

def train_diffusion_ethereum(device):
    from diffusion.collate   import collate_fn
    from diffusion.diff_util import create_diffusion
    from diffusion.model     import DiffusionGNN
    from diffusion.resample  import LossSecondMomentResampler
    from data.ethereum_adapter import load_ethereum_pyg_graphs

    cache_path = DATA_DIR / "ethereum_diffusion_cache.pt"
    out_path   = CKPT_DIR / "diffusion_ethereum" / "model.pt"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"Ethereum Diffusion Training   ({DIFF_ETH_EPOCHS} epochs)")
    print(f"  max_nodes={ETHEREUM_MAX_NODES}  depth={ETHEREUM_DEPTH}")
    print(f"  Save : {out_path}")
    print('='*60)

    NODE_DIM = 6   # 1 label col + 5 structural features (same as Elliptic)

    def _pyg_to_dense(data):
        n = data.x.shape[0]
        x = torch.zeros(n, NODE_DIM)
        x[:, 0] = float(data.y.item())
        x[:, 1:] = data.x
        adj = torch.zeros(n, n)
        ei = data.edge_index
        if ei.shape[1] > 0:
            valid = ei[0] != ei[1]
            src, dst = ei[0][valid], ei[1][valid]
            inb = (src < n) & (dst < n)
            adj[src[inb], dst[inb]] = 1.0
        return x, adj

    if not cache_path.exists():
        kwargs = dict(max_nodes=ETHEREUM_MAX_NODES, depth=ETHEREUM_DEPTH)
        if ETHEREUM_PKL_PATH:
            kwargs["pkl_path"] = ETHEREUM_PKL_PATH
        raw = load_ethereum_pyg_graphs(**kwargs)
        pairs = [(x, a) for g in raw for x, a in [_pyg_to_dense(g)] if g.x.shape[0] >= 3]
        torch.save(pairs, str(cache_path))
        print(f"Saved {len(pairs)} dense pairs → {cache_path}")
    else:
        pairs = torch.load(str(cache_path), weights_only=False)
        if len(pairs) == 0 or pairs[0][0].shape[1] != NODE_DIM:
            cache_path.unlink()
            return train_diffusion_ethereum(device)

    pairs = [(x, a) for x, a in pairs if x.shape[0] <= ETHEREUM_MAX_NODES]
    print(f"Dataset: {len(pairs)} graphs")

    class _DS(Dataset):
        def __getitem__(self, i): return pairs[i]
        def __len__(self): return len(pairs)

    loader   = DataLoader(_DS(), batch_size=DIFF_ETH_BATCH,
                          shuffle=True, collate_fn=collate_fn, drop_last=True)
    all_x    = torch.cat([x for x, _ in pairs], dim=0)
    x_mean   = torch.zeros(NODE_DIM); x_std = torch.ones(NODE_DIM)
    x_mean[1:] = all_x[:, 1:].mean(0); x_std[1:] = all_x[:, 1:].std(0).clamp(min=1e-6)
    x_mean, x_std = x_mean.to(device), x_std.to(device)

    model     = DiffusionGNN(node_dim=NODE_DIM, hidden_dim=DIFF_ETH_HIDDEN,
                             num_layers=DIFF_ETH_LAYERS,
                             class_conditional=DIFF_ETH_CLASS_COND,
                             degree_conditioning=True).to(device)
    diffusion = create_diffusion(T=DIFF_ETH_TIMESTEPS)
    resampler = LossSecondMomentResampler(diffusion)
    optimizer = torch.optim.Adam(model.parameters(), lr=DIFF_ETH_LR)

    # Optional SimCLR alignment loss (active on second training pass)
    frozen_enc_eth = None
    simclr_ckpt_eth = CKPT_DIR / "simclr_ethereum" / "best_model.pt"
    if DIFF_ETH_ALIGN_W > 0 and simclr_ckpt_eth.exists():
        from simclr import GraphEncoder
        from torch_geometric.data import Data as _PygData, Batch as _PygBatch
        _sc = torch.load(str(simclr_ckpt_eth), map_location=device, weights_only=False)
        _sd = _sc["encoder_state_dict"]
        from simclr import encoder_dims_from_state_dict as _edfs_eth
        _in, _hid, _nl, _bn, _gin = _edfs_eth(_sd)
        frozen_enc_eth = GraphEncoder(in_dim=_in, hidden_dim=_hid, out_dim=128,
                                      n_layers=_nl, use_bn=_bn, use_gin=_gin).to(device)
        frozen_enc_eth.load_state_dict(_sd)
        frozen_enc_eth.eval()
        for _p in frozen_enc_eth.parameters():
            _p.requires_grad_(False)
        print(f"  [Alignment] SimCLR checkpoint loaded from {simclr_ckpt_eth.name}")
    else:
        from torch_geometric.data import Data as _PygData, Batch as _PygBatch

    def _lr(ep):
        if ep < DIFF_ETH_WARMUP:
            return (ep + 1) / DIFF_ETH_WARMUP
        p = (ep - DIFF_ETH_WARMUP) / max(1, DIFF_ETH_EPOCHS - DIFF_ETH_WARMUP)
        return 0.5 * (1.0 + math.cos(math.pi * p))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, _lr)
    use_amp   = (str(device) == "cuda")
    scaler    = torch.amp.GradScaler("cuda", enabled=use_amp)
    t0        = time.time()

    for epoch in range(DIFF_ETH_EPOCHS):
        model.train()
        total = 0.0; nb = 0

        for x_batch, adj_batch, mask in loader:
            x_batch   = x_batch.to(device)
            adj_batch = adj_batch.to(device)
            mask      = mask.to(device)
            n_nodes   = x_batch.shape[1]
            nb       += 1

            x_norm = x_batch.clone()
            x_norm[:, :, 1:] = (x_batch[:, :, 1:] - x_mean[1:]) / x_std[1:]
            x_norm = x_norm * mask.unsqueeze(-1)

            if DIFF_ETH_CLASS_COND:
                graph_labels = ((x_batch[:, :, 0] * mask).sum(dim=1) > 0).long()
                null_mask    = torch.rand(graph_labels.shape[0], device=device) < DIFF_ETH_LABEL_DROP
                class_labels = graph_labels.masked_fill(null_mask, 2)
            else:
                class_labels = None

            t, weights = resampler.sample(x_batch.shape[0], device)
            with torch.autocast("cuda", enabled=use_amp):
                x_t, adj_t = diffusion.q_sample(x_norm, t, node_mask=mask, adj_start=adj_batch)
                if DIFF_ETH_EDGE_DROP > 0:
                    drop = torch.bernoulli(
                        torch.full_like(adj_t, 1.0 - DIFF_ETH_EDGE_DROP)
                    )
                    adj_t_in = adj_t * drop
                else:
                    adj_t_in = adj_t
                eps_pred, adj_pred, node_pred = model(
                    x_t, diffusion._scale_timesteps(t),
                    adj=adj_t_in, node_mask=mask,
                    class_labels=class_labels,
                )
                noise_true = x_t[:, :, 1:] - x_norm[:, :, 1:]
                mse = ((eps_pred[:, :, 1:] - noise_true) ** 2 * mask.unsqueeze(-1)).sum() / mask.sum().clamp(1)

            eps_pred_f = eps_pred.float()
            adj_pred_f = adj_pred.float()
            mask_f     = mask.float()
            bce  = F.binary_cross_entropy(
                eps_pred_f[:, :, 0].clamp(1e-6, 1-1e-6) * mask_f,
                x_batch[:, :, 0].float() * mask_f, reduction="sum"
            ) / mask_f.sum().clamp(1)
            _m2 = mask_f[:, :, None] * mask_f[:, None, :]
            adj_l = F.binary_cross_entropy(
                adj_pred_f.clamp(1e-6, 1-1e-6) * _m2,
                adj_batch.float() * _m2, reduction="sum"
            ) / (_m2.sum()).clamp(1)
            pred_dens = adj_pred_f.sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            true_dens = adj_batch.float().sum(dim=(-1, -2)) / (n_nodes ** 2 + 1e-8)
            dens_loss = ((pred_dens - true_dens) ** 2).mean()
            soft_deg  = (adj_pred_f * _m2).sum(dim=-1)
            conn_loss = (F.relu(1.0 - soft_deg) * mask_f).sum() / mask_f.sum().clamp(1)

            align_loss = torch.tensor(0.0, device=device)
            if frozen_enc_eth is not None and nb % DIFF_ETH_ALIGN_EVERY == 0:
                ab_t_v  = torch.tensor(
                    [float(diffusion.alphas_cumprod[int(ti.item())]) for ti in t],
                    dtype=torch.float32, device=device,
                )
                sqrt_ab = ab_t_v.sqrt().view(-1, 1, 1).clamp(min=1e-8)
                sqrt_1m = (1.0 - ab_t_v).sqrt().view(-1, 1, 1)
                x0_cont = (x_t[..., 1:].float().detach() - sqrt_1m * eps_pred_f[..., 1:]) / sqrt_ab
                x0_cont = x0_cont * x_std[1:] + x_mean[1:]
                pyg_pred_list, pyg_real_list = [], []
                for bi in range(x_batch.shape[0]):
                    n_bi = int(mask[bi].sum().item())
                    if n_bi < 2:
                        continue
                    ei_pred = (adj_pred_f[bi, :n_bi, :n_bi].detach() > 0.5).nonzero(as_tuple=False).T.contiguous()
                    ei_real = (adj_batch[bi, :n_bi, :n_bi] > 0.5).nonzero(as_tuple=False).T.contiguous()
                    pyg_pred_list.append(_PygData(x=x0_cont[bi, :n_bi], edge_index=ei_pred))
                    pyg_real_list.append(_PygData(x=x_batch[bi, :n_bi, 1:].detach(), edge_index=ei_real))
                if pyg_pred_list:
                    bp = _PygBatch.from_data_list(pyg_pred_list)
                    br = _PygBatch.from_data_list(pyg_real_list)
                    h_pred = F.normalize(frozen_enc_eth(bp), dim=-1)
                    with torch.no_grad():
                        h_real = F.normalize(frozen_enc_eth(br), dim=-1)
                    align_loss = (1.0 - (h_pred * h_real.detach()).sum(dim=-1)).mean()

            loss = (mse + DIFF_ETH_LAUND_W   * bce
                    + DIFF_ETH_ADJ_W     * adj_l
                    + DIFF_ETH_DENSITY_W * dens_loss
                    + DIFF_ETH_CONN_W    * conn_loss
                    + DIFF_ETH_ALIGN_W   * align_loss)

            optimizer.zero_grad()
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), DIFF_ETH_GRAD_CLIP)
            scaler.step(optimizer); scaler.update()
            total += loss.item()

        scheduler.step()
        if (epoch + 1) % 10 == 0 or epoch < 3:
            print(f"Epoch {epoch+1:4d}/{DIFF_ETH_EPOCHS} | "
                  f"loss={total/max(nb,1):.4f} | {time.time()-t0:.0f}s")

        torch.save({"model": model.state_dict(),
                    "x_mean": x_mean.cpu(), "x_std": x_std.cpu(),
                    "class_conditional": DIFF_ETH_CLASS_COND,
                    "num_layers": DIFF_ETH_LAYERS,
                    "degree_conditioning": True,
                    "max_nodes": ETHEREUM_MAX_NODES}, out_path)

    print(f"\nEthereum diffusion checkpoint saved → {out_path}")


# ─────────────────────────────────────────────────────────────────────────────
# Ethereum Phishing — SimCLR training
# ─────────────────────────────────────────────────────────────────────────────

def train_simclr_ethereum(device):
    from simclr import GraphEncoder, ProjectionHead, OnlineProbeHead, nt_xent_loss, sup_con_loss, _is_connected_ei
    from torch_geometric.data import Data, Batch
    from diffusion.model     import DiffusionGNN
    from diffusion.diff_util import create_diffusion
    from data.ethereum_adapter import load_ethereum_pyg_graphs

    ckpt_dir  = CKPT_DIR / "simclr_ethereum"
    diff_ckpt = CKPT_DIR / "diffusion_ethereum" / "model.pt"
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"Ethereum SimCLR Training   ({SIMCLR_ETH_EPOCHS} epochs)")
    print(f"  max_nodes={ETHEREUM_MAX_NODES}  depth={ETHEREUM_DEPTH}")
    print(f"  Save : {ckpt_dir}")
    print('='*60)

    kwargs = dict(max_nodes=ETHEREUM_MAX_NODES, depth=ETHEREUM_DEPTH)
    if ETHEREUM_PKL_PATH:
        kwargs["pkl_path"] = ETHEREUM_PKL_PATH
    raw_graphs = load_ethereum_pyg_graphs(**kwargs)

    def _extend_6d(g):
        n = g.x.shape[0]
        lc = torch.full((n, 1), float(g.y.item()))
        x6 = torch.cat([lc, g.x], dim=1)
        return Data(x=x6, edge_index=g.edge_index.clone(), y=g.y.clone())

    graphs = [_extend_6d(g) for g in raw_graphs]
    n_ph   = sum(g.y.item() == 1 for g in graphs)
    print(f"  {len(graphs)} graphs ({n_ph} phishing, {len(graphs)-n_ph} clean)")

    diff_model = diffusion = x_mean = x_std = None
    if diff_ckpt.exists():
        ckpt            = torch.load(str(diff_ckpt), map_location=device, weights_only=False)
        class_cond_ckpt = ckpt.get("class_conditional", False)
        num_layers_ckpt = ckpt.get("num_layers", 3)
        deg_cond_ckpt   = ckpt.get("degree_conditioning", True)
        diff_model = DiffusionGNN(node_dim=6, hidden_dim=DIFF_ETH_HIDDEN,
                                  num_layers=num_layers_ckpt,
                                  class_conditional=class_cond_ckpt,
                                  degree_conditioning=deg_cond_ckpt).to(device)
        diff_model.load_state_dict(ckpt["model"])
        diff_model.eval()
        diffusion = create_diffusion(T=DIFF_ETH_TIMESTEPS)
        x_mean    = ckpt["x_mean"].to(device)
        x_std     = ckpt["x_std"].to(device)
        print(f"  Diffusion augmentation enabled (class_conditional={class_cond_ckpt}).")
    else:
        print(f"  Diffusion checkpoint not found — structural augmentation only.")

    def _augment(g, p_edge=SIMCLR_ETH_P_EDGE_DROP, p_feat=SIMCLR_ETH_P_FEAT_MASK):
        x  = g.x.clone()
        mask = torch.rand(x.shape[0], x.shape[1] - 1) > p_feat
        x[:, 1:] *= mask.float()
        ei = g.edge_index
        if ei.shape[1] > 0:
            n_edges = ei.shape[1] // 2
            keep     = torch.rand(n_edges) > p_edge
            keep_idx = keep.repeat_interleave(2).nonzero(as_tuple=False).squeeze(1)
            ei = ei[:, keep_idx] if len(keep_idx) > 0 else torch.zeros(2, 0, dtype=torch.long)
        return Data(x=x[:, 1:], edge_index=ei, y=g.y.clone())

    def _diff_view(g):
        if diff_model is None:
            return None
        n = g.x.shape[0]
        x_pad  = torch.zeros(1, ETHEREUM_MAX_NODES, 6, device=device)
        a_pad  = torch.zeros(1, ETHEREUM_MAX_NODES, ETHEREUM_MAX_NODES, device=device)
        msk    = torch.zeros(1, ETHEREUM_MAX_NODES, device=device)
        x_pad[0, :n]     = g.x.to(device)
        msk[0, :n]       = 1.0
        ei = g.edge_index
        if ei.shape[1] > 0:
            valid = ei[0] != ei[1]
            s, d  = ei[0][valid], ei[1][valid]
            inb   = (s < n) & (d < n)
            a_pad[0, s[inb], d[inb]] = 1.0
        x_n = x_pad.clone()
        x_n[:, :, 1:] = (x_pad[:, :, 1:] - x_mean[1:]) / x_std[1:]
        x_n = x_n * msk.unsqueeze(-1)
        t_frac = random.uniform(0.1, 0.4)
        t_val  = max(1, int(t_frac * DIFF_ETH_TIMESTEPS))
        t      = torch.tensor([t_val], device=device)
        x_t, adj_t = diffusion.q_sample(x_n, t, node_mask=msk, adj_start=a_pad)
        try:
            with torch.no_grad():
                ep, ap, _ = diff_model(x_t, diffusion._scale_timesteps(t),
                                       adj=adj_t, node_mask=msk)
                x0_c = diffusion._predict_xstart_from_eps(x_t[..., 1:], t, ep[..., 1:])
                x0_b = ep[..., 0:1].clamp(0.0, 1.0)
            x0     = torch.cat([x0_b, x0_c], dim=-1)[0, :n].cpu()
            x0[:, 1:] = x0[:, 1:] * x_std[1:].cpu() + x_mean[1:].cpu()
            deg    = ap[0, :n, :n].cpu().sum(-1)
            x0[:, 1] = deg / deg.max().clamp(min=1.0)
            ei_out = (ap[0, :n, :n].cpu() > 0.5).nonzero(as_tuple=False).T.contiguous()
            return Data(x=x0[:, 1:], edge_index=ei_out, y=g.y.clone())
        except Exception:
            return None

    # in_dim=5: label column stripped before encoder (label-leakage fix)
    encoder    = GraphEncoder(in_dim=5, hidden_dim=128, out_dim=128,
                              n_layers=3, use_bn=True).to(device)
    projector  = ProjectionHead(in_dim=128, proj_dim=64).to(device)
    eth_probe  = OnlineProbeHead(in_dim=128).to(device) if SIMCLR_ETH_PROBE_W > 0 else None
    all_params = (list(encoder.parameters()) + list(projector.parameters())
                  + (list(eth_probe.parameters()) if eth_probe else []))
    optimizer  = torch.optim.Adam(all_params, lr=SIMCLR_ETH_LR)

    best_loss = float("inf")
    t0        = time.time()

    for epoch in range(SIMCLR_ETH_EPOCHS):
        encoder.train(); projector.train()
        if eth_probe: eth_probe.train()
        if diff_model: diff_model.eval()
        random.shuffle(graphs)
        total = nx_t = sc_t = probe_t = 0.0; nb = 0

        for i in range(0, len(graphs), SIMCLR_ETH_BATCH):
            batch = graphs[i : i + SIMCLR_ETH_BATCH]
            v1, v2, lbls = [], [], []
            for g in batch:
                v1.append(_augment(g))
                if diff_model and random.random() < SIMCLR_ETH_P_DIFFUSION:
                    dv = _diff_view(g)
                    if dv is not None and not _is_connected_ei(dv.edge_index, dv.x.shape[0]):
                        dv = None
                    v2.append(dv if dv is not None else _augment(g))
                else:
                    v2.append(_augment(g))
                lbls.append(int(g.y.item()))

            labels = torch.tensor(lbls, dtype=torch.long, device=device)
            b1 = Batch.from_data_list(v1).to(device)
            b2 = Batch.from_data_list(v2).to(device)

            optimizer.zero_grad()
            h1 = encoder(b1); h2 = encoder(b2)
            z1 = projector(h1); z2 = projector(h2)
            ntxent  = nt_xent_loss(z1, z2, temperature=SIMCLR_ETH_NTXENT_T)
            z_all   = torch.cat([z1, z2]); lbl_all = torch.cat([labels, labels])
            sc      = sup_con_loss(z_all, lbl_all, temperature=SIMCLR_ETH_SUPCON_T)

            if eth_probe is not None:
                h_all       = torch.cat([h1.float(), h2.float()], dim=0)
                probe_logit = eth_probe(F.normalize(h_all, dim=-1))
                probe_loss  = F.binary_cross_entropy_with_logits(probe_logit, lbl_all.float())
            else:
                probe_loss = torch.tensor(0.0, device=device)

            loss = ntxent + SIMCLR_ETH_SUPCON_W * sc + SIMCLR_ETH_PROBE_W * probe_loss
            loss.backward(); optimizer.step()

            total   += loss.item()
            nx_t    += ntxent.item()
            sc_t    += sc.item() if isinstance(sc, torch.Tensor) else float(sc)
            probe_t += probe_loss.item()
            nb      += 1

        avg       = total   / max(nb, 1)
        probe_str = f", probe={probe_t/max(nb,1):.4f}" if eth_probe else ""
        print(f"Epoch {epoch+1:3d}/{SIMCLR_ETH_EPOCHS} | "
              f"loss={avg:.4f} (nt_xent={nx_t/max(nb,1):.4f}, "
              f"supcon={sc_t/max(nb,1):.4f}{probe_str}) | "
              f"{time.time()-t0:.1f}s")

        _ckpt_data = {
            "encoder_state_dict":   encoder.state_dict(),
            "projector_state_dict": projector.state_dict(),
            "probe_state_dict":     eth_probe.state_dict() if eth_probe else None,
            "loss": avg, "epoch": epoch + 1,
        }
        if (epoch + 1) % SIMCLR_ETH_CKPT_EVERY == 0:
            torch.save(_ckpt_data, ckpt_dir / f"epoch_{epoch+1}.pt")

        if avg < best_loss:
            best_loss = avg
            torch.save(_ckpt_data, ckpt_dir / "best_model.pt")

    print(f"\nEthereum SimCLR checkpoints saved → {ckpt_dir}  (best loss={best_loss:.4f})")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="AML graph generation — master training script")
    parser.add_argument("--dataset", choices=["ibm", "elliptic", "ethereum"], default=DATASET,
                        help=f"Dataset to train on (default: {DATASET})")
    parser.add_argument("--phase", choices=["diffusion", "simclr", "all"], default="all",
                        help="Which phase to run (default: all)")
    parser.add_argument("--ibm-csv", type=str, default=None,
                        help="Override IBM CSV path (overrides IBM_CSV_PATH in CONFIG)")
    parser.add_argument("--ckpt-dir", type=str, default=None,
                        help="Root checkpoint directory; diffusion saved to <dir>/diffusion/, "
                             "simclr to <dir>/simclr/ (default: checkpoints/diffusion_ibm + "
                             "checkpoints/simclr_ibm)")
    args = parser.parse_args()

    if args.ibm_csv:
        global IBM_CSV_PATH
        IBM_CSV_PATH = args.ibm_csv

    if args.ckpt_dir:
        global IBM_DIFF_CKPT_DIR, IBM_SIMCLR_CKPT_DIR
        IBM_DIFF_CKPT_DIR   = Path(args.ckpt_dir) / "diffusion"
        IBM_SIMCLR_CKPT_DIR = Path(args.ckpt_dir) / "simclr"

    dataset = args.dataset
    device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device  : {device}")
    print(f"Dataset : {dataset}")
    print(f"Phase   : {args.phase}")

    if dataset == "ibm":
        if args.phase in ("diffusion", "all"):
            train_diffusion_ibm(device)
        if args.phase in ("simclr", "all"):
            train_simclr_ibm(device)
    elif dataset == "ethereum":
        if args.phase in ("diffusion", "all"):
            train_diffusion_ethereum(device)
        if args.phase in ("simclr", "all"):
            train_simclr_ethereum(device)
    else:
        if args.phase in ("diffusion", "all"):
            train_diffusion_elliptic(device)
        if args.phase in ("simclr", "all"):
            train_simclr_elliptic(device)

    print("\nTraining complete.")


if __name__ == "__main__":
    main()
