"""
viz_real_generated.py
──────────────────────────────────────────────────────────────────────────────
Visualise REAL IBM subgraphs and the graphs that were ACTUALLY generated by the
diffusion + SimCLR pipeline.  Loads directly from the on-disk caches so no
model re-running is required.

Three figures are produced:

  1. generation_pipeline.png
     4-row × 3-col grid.  Each row is one laundering seed:
       col A – Real seed subgraph (from networks_cache)
       col B – SimCLR structural augmentation view of the same seed
       col C – A diffusion-generated laundering subgraph (from gen_cache)

  2. generated_gallery.png
     4×4 gallery of generated laundering subgraphs showing structural variety.

  3. seed_gallery.png
     4×4 gallery of real laundering seed subgraphs for direct comparison.

Usage (run from igraph_version/ or the repo root):
    python viz_real_generated.py
    python viz_real_generated.py --out thesis_figures/
    python viz_real_generated.py \\
        --net-cache data/networks_cache_LI-Small_Trans_v2.pkl \\
        --gen-cache data/gen_cache_LI-Small_Trans_n500_t150_ld10_encenc_full.pkl \\
        --out figures_real --seed 7
"""

import argparse
import pickle
import random
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import networkx as nx
import numpy as np
import torch

# ── path setup so we can import from simclr/, diffusion/, generation/ ────────
_ROOT = Path(__file__).resolve().parent          # igraph_version/
for _p in (_ROOT, _ROOT / "simclr", _ROOT / "diffusion", _ROOT / "generation"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

# Default cache paths
DEFAULT_NET_CACHE = _ROOT / "data" / "networks_cache_LI-Small_Trans_v2.pkl"
DEFAULT_GEN_CACHE = _ROOT / "data" / "gen_cache_LI-Small_Trans_n500_t150_ld10_encenc_full.pkl"

# ── Visual style ──────────────────────────────────────────────────────────────
C_LAUND   = "#e63946"   # red     — laundering node
C_CLEAN   = "#457b9d"   # blue    — clean node
C_GEN     = "#8338ec"   # purple  — generated node (unknown per-node label)
C_GHOST   = "#ced4da"   # grey    — cropped-out ghost node
C_EDGE    = "#343a40"   # dark    — active edge
C_REM_E   = "#e63946"   # red     — removed edge (dashed)
C_GEN_E   = "#6a4c93"   # purple  — generated graph edge


# ── Network dict → NetworkX ───────────────────────────────────────────────────

def net_to_nx(net) -> nx.DiGraph:
    """Convert an IBM network dict (igraph or transactions) to NetworkX."""
    g = net.get("graph")
    if g is not None:
        G = nx.DiGraph()
        names = g.vs["name"] if "name" in g.vs.attributes() else list(range(g.vcount()))
        G.add_nodes_from(names)
        for e in g.es:
            G.add_edge(names[e.source], names[e.target])
        return G
    txs = net.get("transactions")
    if txs is not None and len(txs) > 0:
        G = nx.DiGraph()
        for _, row in txs.iterrows():
            s, t = int(row["From_Account_int"]), int(row["To_Account_int"])
            if s != t:
                G.add_edge(s, t)
        return G
    return nx.DiGraph()


def _node_colors(G, laundering, collapsed=None):
    collapsed = collapsed or set()
    out = []
    for n in G.nodes():
        if n in laundering:
            out.append(C_LAUND)
        else:
            out.append(C_CLEAN)
    return out


def _draw_seed_panel(ax, G, net, title, ghost_nodes=None, ghost_edges=None,
                     removed_edges=None):
    """Draw a real seed panel (or its augmented view) with laundering colours."""
    laundering   = net.get("laundering_nodes", set())
    start        = net.get("start_node")
    ghost_nodes  = ghost_nodes  or set()
    ghost_edges  = ghost_edges  or set()
    removed_edges = removed_edges or set()

    n_nodes = G.number_of_nodes()
    if n_nodes == 0:
        ax.text(0.5, 0.5, "empty", ha="center", va="center",
                transform=ax.transAxes, color="grey", fontsize=9)
        ax.axis("off")
        return

    k = 2.2 / max(n_nodes ** 0.5, 1)
    try:
        pos = nx.spring_layout(G, seed=42, k=k, iterations=80)
    except Exception:
        pos = nx.random_layout(G, seed=42)

    # Ghost nodes (cropped out)
    ghosts = [n for n in G.nodes() if n in ghost_nodes]
    active = [n for n in G.nodes() if n not in ghost_nodes]

    if ghosts:
        nx.draw_networkx_nodes(G, pos, ax=ax, nodelist=ghosts,
                               node_color=C_GHOST, node_size=200, alpha=0.3,
                               edgecolors=C_GHOST, linewidths=0.5)

    if active:
        colors = _node_colors(G.subgraph(active), laundering)
        sizes  = [300 if n in laundering else 200 for n in active]
        edge_c = ["#f1c40f" if n == start else "white" for n in active]
        lw     = [2.5     if n == start else 1.2  for n in active]
        nx.draw_networkx_nodes(G, pos, ax=ax, nodelist=active,
                               node_color=colors, node_size=sizes,
                               edgecolors=edge_c, linewidths=lw, alpha=0.95)

    # Ghost edges
    ghost_el = [(u, v) for u, v in G.edges() if (u, v) in ghost_edges]
    if ghost_el:
        nx.draw_networkx_edges(G, pos, ax=ax, edgelist=ghost_el,
                               edge_color=C_GHOST, style="dashed", alpha=0.3,
                               arrows=False, width=0.8)

    # Removed edges (shown dashed red)
    rem_el = [(u, v) for u, v in G.edges() if (u, v) in removed_edges
              and (u, v) not in ghost_edges]
    # Normal active edges
    normal_el = [(u, v) for u, v in G.edges()
                 if (u, v) not in ghost_edges and (u, v) not in removed_edges]

    if normal_el:
        nx.draw_networkx_edges(G, pos, ax=ax, edgelist=normal_el,
                               edge_color=C_EDGE, arrows=True,
                               arrowstyle="-|>", arrowsize=10, width=1.3,
                               connectionstyle="arc3,rad=0.06", alpha=0.75)
    if rem_el:
        nx.draw_networkx_edges(G, pos, ax=ax, edgelist=rem_el,
                               edge_color=C_REM_E, style="dashed", alpha=0.45,
                               arrows=True, arrowstyle="-|>", arrowsize=8,
                               width=1.2, connectionstyle="arc3,rad=0.06")

    ax.set_title(title, fontsize=18, fontweight="bold", pad=6)
    ax.axis("off")


def _draw_generated_panel(ax, data, title):
    """
    Draw a generated graph.

    data can be either:
      • A PyG Data object (from the gen_cache) — node colours fall back to
        betweenness centrality as a proxy for laundering likelihood, because
        the gen_cache does not store per-node laundering flags.
      • A dict {"adj": Tensor[n,n], "n": int, "laund_flags": ndarray[bool,n]}
        from generate_with_labels() — node colours are the actual model
        predictions (x_out[:,0] > 0.5) from the diffusion output.
    """
    # ── parse the two possible input formats ─────────────────────────────────
    if isinstance(data, dict):
        adj          = data["adj"]          # [n, n] tensor
        n            = data["n"]
        laund_flags  = data["laund_flags"]  # bool array, length n
        use_model_labels = True

        G = nx.DiGraph()
        G.add_nodes_from(range(n))
        ei_np = adj.nonzero(as_tuple=False).numpy()
        for r, c in ei_np:
            if r != c:
                G.add_edge(int(r), int(c))

        # Node size ∝ total degree
        sizes = np.array(
            [max(80, 40 * (G.in_degree(v) + G.out_degree(v) + 1))
             for v in G.nodes()], dtype=float
        )
        sizes = np.clip(sizes, 80, 500).tolist()

    else:
        pyg_data = data
        ei       = pyg_data.edge_index
        n        = pyg_data.x.shape[0]
        x_feat   = pyg_data.x
        use_model_labels = False

        if n == 0 or (ei.shape[1] == 0 and n < 2):
            ax.text(0.5, 0.5, "empty", ha="center", va="center",
                    transform=ax.transAxes, color="grey", fontsize=9)
            ax.axis("off")
            return

        G = nx.DiGraph()
        G.add_nodes_from(range(n))
        if ei.shape[1] > 0:
            ei_np = ei.cpu().numpy()
            for s, t in zip(ei_np[0], ei_np[1]):
                if s != t:
                    G.add_edge(int(s), int(t))

        # Betweenness centrality fallback when per-node labels are unavailable
        try:
            bc = nx.betweenness_centrality(G.to_undirected())
        except Exception:
            bc = {node: 0.0 for node in G.nodes()}

        bc_vals  = np.array([bc[v] for v in G.nodes()])
        bc_range = bc_vals.max() - bc_vals.min()
        threshold   = (bc_vals.min() + 0.3 * bc_range) if bc_range > 0 else bc_vals.max() + 1
        laund_flags = bc_vals >= threshold

        deg_norm = x_feat[:, 0].cpu().numpy()
        sizes    = np.clip(deg_norm * 400 + 80, 80, 500).tolist()

    # ── layout ────────────────────────────────────────────────────────────────
    if G.number_of_nodes() == 0:
        ax.axis("off")
        return

    k = 2.0 / max(n ** 0.5, 1)
    try:
        pos = nx.spring_layout(G, seed=42, k=k, iterations=80)
    except Exception:
        pos = nx.random_layout(G, seed=42)

    colors = [C_LAUND if lf else C_CLEAN for lf in laund_flags]

    nx.draw_networkx_nodes(G, pos, ax=ax,
                           node_color=colors, node_size=sizes,
                           edgecolors="white", linewidths=1.4, alpha=0.92)

    if G.number_of_edges() > 0:
        nx.draw_networkx_edges(G, pos, ax=ax,
                               edge_color=C_EDGE, arrows=True,
                               arrowstyle="-|>", arrowsize=9, width=1.2,
                               connectionstyle="arc3,rad=0.06", alpha=0.60)

    ax.set_title(title, fontsize=18, fontweight="bold", pad=6)
    ax.axis("off")


# ── Real guided generation with per-node labels ───────────────────────────────

def generate_with_labels(networks, n_gen=12, t_start=150, seed=42,
                          max_encode=2000, probe_epochs=200):
    """
    Run the actual guided diffusion pipeline and return per-node laundering
    labels from the model's own x_out[:,0] prediction.

    Returns a list of dicts:
        {"laund_flags": ndarray[bool, n], "adj": Tensor[n,n], "n": int}
    or None if the model checkpoints cannot be found.
    """
    try:
        from generation import (load_simclr_encoder, load_diffusion_model,
                                 encode_all_networks, train_mlp_probe,
                                 guided_generate)
    except ImportError as e:
        print(f"  [warn] generation import failed: {e}")
        return None

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"  Running generation on {device}")

    try:
        encoder = load_simclr_encoder(device)
    except FileNotFoundError as e:
        print(f"  [warn] {e}")
        return None

    try:
        diff_model, diffusion, x_mean, x_std, max_nodes = load_diffusion_model(device)
    except Exception as e:
        print(f"  [warn] diffusion model load failed: {e}")
        return None

    # Encode a balanced subset for probe training (keeps runtime manageable)
    rng_enc   = random.Random(seed + 1)
    laund_all = [n for n in networks if len(n.get("laundering_nodes", set())) > 0]
    clean_all = [n for n in networks if len(n.get("laundering_nodes", set())) == 0]
    n_each    = min(max_encode // 2, len(laund_all), len(clean_all))
    enc_subset = rng_enc.sample(laund_all, n_each) + rng_enc.sample(clean_all, n_each)
    rng_enc.shuffle(enc_subset)

    print(f"  Encoding {len(enc_subset)} networks for probe training ...")
    H_all_n, y_all = encode_all_networks(enc_subset, encoder, device)
    probe = train_mlp_probe(H_all_n, y_all, device, n_epochs=probe_epochs)

    # Generate from laundering seeds
    rng_gen = random.Random(seed)
    seeds   = rng_gen.sample(laund_all, min(n_gen + 5, len(laund_all)))

    results = []
    print(f"  Generating {n_gen} graphs (t_start={t_start}) ...")
    for seed_net in seeds:
        if len(results) >= n_gen:
            break
        try:
            x_out, adj_out, n_out, _ = guided_generate(
                seed_net, encoder, probe, diff_model, diffusion,
                x_mean, x_std, H_all_n, device,
                target_label=1, t_start=t_start,
            )
            # x_out[:, 0] is a graph-level laundering signal (the guidance
            # pushes all nodes uniformly) rather than a reliable per-node label.
            # Betweenness centrality on the generated graph structure is the
            # right structural proxy: laundering intermediaries sit at bottlenecks.
            G_tmp = nx.DiGraph()
            G_tmp.add_nodes_from(range(n_out))
            for r, c in adj_out[:n_out, :n_out].nonzero(as_tuple=False).numpy():
                if r != c:
                    G_tmp.add_edge(int(r), int(c))
            try:
                bc = nx.betweenness_centrality(G_tmp.to_undirected())
            except Exception:
                bc = {v: 0.0 for v in G_tmp.nodes()}
            bc_vals  = np.array([bc.get(v, 0.0) for v in range(n_out)])
            bc_range = bc_vals.max() - bc_vals.min()
            # Range-based threshold: top 30% of the BC range.  Works correctly
            # for star graphs where most nodes have BC=0 (only the hub is labeled).
            thresh = (bc_vals.min() + 0.3 * bc_range) if bc_range > 0 else bc_vals.max() + 1
            laund_flags = bc_vals >= thresh
            results.append({
                "laund_flags": laund_flags,
                "adj":         adj_out[:n_out, :n_out],
                "n":           n_out,
            })
        except Exception as e:
            print(f"  [warn] generation failed for one seed: {e}")

    print(f"  Generated {len(results)} graphs with per-node labels.")
    return results if results else None


# ── Load caches ───────────────────────────────────────────────────────────────

def load_network_cache(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Network cache not found: {path}")
    print(f"Loading network cache: {path.name} ...")
    with open(path, "rb") as f:
        networks = pickle.load(f)
    # Rebuild igraph objects
    try:
        from augmentation import build_igraph_from_transactions
        for net in networks:
            if "graph" not in net and "transactions" in net:
                net["graph"] = build_igraph_from_transactions(net["transactions"])
    except ImportError:
        print("  [warn] igraph augmentation module not found; igraph graphs not rebuilt.")
    n_laund = sum(1 for n in networks if len(n.get("laundering_nodes", set())) > 0)
    print(f"  {len(networks)} networks  ({n_laund} laundering, {len(networks)-n_laund} clean)")
    return networks


def load_gen_cache(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Gen cache not found: {path}")
    print(f"Loading gen cache: {path.name} ...")
    with open(path, "rb") as f:
        gen_data = pickle.load(f)
    n_laund = sum(1 for d in gen_data if d.y.item() == 1)
    print(f"  {len(gen_data)} generated graphs  ({n_laund} laundering)")
    return gen_data


# ── SimCLR augmentation ───────────────────────────────────────────────────────

def apply_simclr_aug(net, rng_seed=0, min_keep_frac=0.35):
    """
    Apply one structural augmentation view to a seed network.

    Uses an undirected BFS for the crop step so that sink-type laundering
    nodes (high in-degree, low out-degree) don't produce a near-empty view.
    Falls back to the original if the augmented view is too small.

    Returns (G_orig, ghost_nodes, ghost_edges, removed_edges).
    """
    G_orig = net_to_nx(net)
    n_orig = G_orig.number_of_nodes()

    if n_orig == 0:
        return G_orig, set(), set(), set()

    # Use NetworkX undirected view for BFS so sink nodes are reachable
    G_undir = G_orig.to_undirected()

    # Pick start node: prefer a laundering node that actually has edges
    laundering = net.get("laundering_nodes", set())
    candidates = [n for n in G_undir.nodes()
                  if n in laundering and G_undir.degree(n) > 0]
    if not candidates:
        candidates = [n for n in G_undir.nodes() if G_undir.degree(n) > 0]
    if not candidates:
        return G_orig, set(), set(), set()

    rng = random.Random(rng_seed)
    start_node = rng.choice(candidates)

    # BFS in undirected mode — yields nodes in BFS order
    crop_ratio = rng.uniform(0.65, 0.80)
    bfs_nodes = [start_node] + [v for _, v in nx.bfs_edges(G_undir, start_node)]
    keep_n = max(2, int(len(bfs_nodes) * crop_ratio))
    kept = set(bfs_nodes[:keep_n])

    # If kept fraction is too small, increase to avoid near-empty panels
    if len(kept) < max(2, min_keep_frac * n_orig):
        kept = set(bfs_names)    # no crop — show edge-drop only

    ghost_ns = set(G_orig.nodes()) - kept

    # Determine ghost/removed edges
    orig_edges = set(G_orig.edges())
    ghost_es   = {e for e in orig_edges if e[0] in ghost_ns or e[1] in ghost_ns}

    # Edge deletion: remove a random ~20% of non-bridge edges in kept subgraph
    kept_edges = [e for e in orig_edges if e[0] not in ghost_ns and e[1] not in ghost_ns]
    G_kept = G_orig.subgraph(kept).copy()
    try:
        G_kept_undir = G_kept.to_undirected()
        bridges = {(min(u, v), max(u, v)) for u, v in nx.bridges(G_kept_undir)}
        non_bridges = [e for e in kept_edges
                       if (min(e[0], e[1]), max(e[0], e[1])) not in bridges]
    except Exception:
        non_bridges = list(kept_edges)

    n_del = max(1, int(len(non_bridges) * rng.uniform(0.10, 0.25)))
    rng.shuffle(non_bridges)
    removed_es = set(non_bridges[:n_del])

    return G_orig, ghost_ns, ghost_es, removed_es


# ── Figure 1: Pipeline ────────────────────────────────────────────────────────

def make_pipeline_figure(networks, gen_data, gen_labeled, out_dir, n_rows=3, seed=42):
    """Show (seed | aug view | generated) for n_rows laundering examples.

    gen_labeled: list of dicts from generate_with_labels() with real model
                 per-node laundering predictions, or None to fall back to
                 betweenness heuristic on gen_data.
    """
    rng = random.Random(seed)

    laund_nets = [n for n in networks if len(n.get("laundering_nodes", set())) > 0]

    if not laund_nets:
        print("[skip] No laundering networks found in cache.")
        return

    # Pick seeds where the augmented view keeps a meaningful fraction of nodes.
    candidates = list(laund_nets)
    rng.shuffle(candidates)
    accepted = []
    for net in candidates:
        if len(accepted) >= n_rows:
            break
        n_nodes = net_to_nx(net).number_of_nodes()
        if n_nodes < 5:
            continue
        aug_seed = rng.randint(0, 9999)
        G_orig, ghost_ns, ghost_es, removed_es = apply_simclr_aug(
            net, rng_seed=aug_seed, min_keep_frac=0.40
        )
        kept_frac = (G_orig.number_of_nodes() - len(ghost_ns)) / max(G_orig.number_of_nodes(), 1)
        if kept_frac < 0.35 or (G_orig.number_of_nodes() - len(ghost_ns)) < 4:
            continue
        accepted.append((net, G_orig, ghost_ns, ghost_es, removed_es))

    if not accepted:
        print("[warn] Could not find seeds with good augmentation; using all candidates.")
        accepted = [(net, net_to_nx(net), set(), set(), set())
                    for net in candidates[:n_rows]]

    # Col C data: prefer real model labels, fall back to gen_cache + betweenness
    use_model_labels = gen_labeled is not None and len(gen_labeled) >= len(accepted)
    if use_model_labels:
        gen_col = gen_labeled[:len(accepted)]
    else:
        laund_gen = [d for d in gen_data if d.y.item() == 1]
        if not laund_gen:
            print("[skip] No generated laundering graphs in gen cache.")
            return
        gen_col = rng.sample(laund_gen, min(len(accepted), len(laund_gen)))

    fig, axes = plt.subplots(n_rows, 3, figsize=(18, n_rows * 6.0))
    if n_rows == 1:
        axes = [axes]

    col_labels = [
        "Real Seed Subgraph\n(from IBM AML dataset)",
        "SimCLR Augmented View\n(subgraph crop + edge deletion)",
        "Diffusion-Generated Subgraph\n(guided reverse diffusion, label=1)",
    ]

    for row_i, ((net, G_orig, ghost_ns, ghost_es, removed_es), gen_item) in enumerate(
        zip(accepted, gen_col)
    ):
        G_seed = net_to_nx(net)

        _draw_seed_panel(
            axes[row_i][0], G_seed, net,
            title=f"Seed #{row_i+1}  [LAUNDERING]",
        )
        _draw_seed_panel(
            axes[row_i][1], G_orig, net,
            title="SimCLR Augmented View",
            ghost_nodes=ghost_ns,
            ghost_edges=ghost_es,
            removed_edges=removed_es,
        )
        _draw_generated_panel(
            axes[row_i][2], gen_item,
            title=f"Generated #{row_i+1}  [label=1]",
        )

    for col_i, label in enumerate(col_labels):
        axes[0][col_i].set_title(label, fontsize=18, fontweight="bold", pad=8,
                                 color="#2c2c2c")

    label_src = "top-30% betweenness"
    handles = [
        mpatches.Patch(color=C_LAUND, label="Laundering node (cols A–B: ground truth)"),
        mpatches.Patch(color=C_CLEAN, label="Clean node"),
        mpatches.Patch(color=C_GHOST, alpha=0.5, label="Cropped-out node"),
        mpatches.Patch(color=C_REM_E, alpha=0.5, label="Removed edge (dashed)"),
        mpatches.Patch(color=C_LAUND, label=f"Laundering node (col C: {label_src})"),
    ]
    fig.legend(handles=handles, loc="lower center", ncol=3,
               fontsize=16, frameon=True, edgecolor="#dee2e6",
               bbox_to_anchor=(0.5, -0.01))

    fig.suptitle(
        "IBM AML Subgraph Generation Pipeline\n"
        "Real seed (left)  →  SimCLR augmented view (centre)  →  Diffusion-generated (right)",
        fontsize=22, fontweight="bold",
    )
    plt.tight_layout(rect=[0, 0.06, 1, 0.96])
    _save(fig, out_dir, "generation_pipeline")


# ── Figure 2: Generated gallery ───────────────────────────────────────────────

def make_generated_gallery(gen_data, gen_labeled, out_dir, nrows=3, ncols=3, seed=42):
    """3×3 gallery of diffusion-generated laundering subgraphs.

    gen_labeled: list of dicts from generate_with_labels(), or None to fall
                 back to the gen_cache with betweenness heuristic coloring.
    """
    n_panels = nrows * ncols
    use_model_labels = gen_labeled is not None and len(gen_labeled) >= 1

    if use_model_labels:
        rng = random.Random(seed)
        sel = gen_labeled[:n_panels]
    else:
        rng   = random.Random(seed)
        laund = [d for d in gen_data if d.y.item() == 1]
        if not laund:
            print("[skip] No generated laundering graphs.")
            return
        sel = rng.sample(laund, min(n_panels, len(laund)))

    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * 5.5, nrows * 5.5))
    axes = np.array(axes).flatten()

    for i, (ax, item) in enumerate(zip(axes, sel)):
        _draw_generated_panel(ax, item, title=f"Generated #{i+1}")

    for ax in axes[len(sel):]:
        ax.set_visible(False)

    label_src = "top-30% betweenness"
    handles = [
        mpatches.Patch(color=C_LAUND, label=f"Laundering node ({label_src})"),
        mpatches.Patch(color=C_CLEAN, label="Non-laundering node"),
    ]
    fig.legend(handles=handles, loc="lower center", ncol=2,
               fontsize=16, frameon=True, edgecolor="#dee2e6",
               bbox_to_anchor=(0.5, -0.01))

    fig.suptitle(
        "Gallery: Diffusion-Generated Laundering Subgraphs (IBM AML)\n"
        "All graphs steered toward label=1 via SimCLR-guided reverse diffusion",
        fontsize=22, fontweight="bold",
    )
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    _save(fig, out_dir, "generated_gallery")


# ── Figure 3: Real seed gallery ───────────────────────────────────────────────

def make_seed_gallery(networks, out_dir, nrows=3, ncols=3, seed=42):
    """3×3 gallery of real laundering seed subgraphs for comparison."""
    rng     = random.Random(seed)
    laund   = [n for n in networks if len(n.get("laundering_nodes", set())) > 0]
    if not laund:
        print("[skip] No laundering networks for seed gallery.")
        return
    sel = rng.sample(laund, min(nrows * ncols, len(laund)))

    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols * 5.5, nrows * 5.5))
    axes = np.array(axes).flatten()

    for i, (ax, net) in enumerate(zip(axes, sel)):
        G = net_to_nx(net)
        _draw_seed_panel(ax, G, net, title=f"Seed #{i+1}  [LAUNDERING]")

    for ax in axes[len(sel):]:
        ax.set_visible(False)

    handles = [
        mpatches.Patch(color=C_LAUND, label="Laundering node"),
        mpatches.Patch(color=C_CLEAN, label="Clean node"),
    ]
    fig.legend(handles=handles, loc="lower center", ncol=2,
               fontsize=12, frameon=True, edgecolor="#dee2e6",
               bbox_to_anchor=(0.5, -0.01))

    fig.suptitle(
        "Gallery: Real Laundering Seed Subgraphs (IBM AML Dataset)\n"
        "Ego-subgraphs extracted around flagged transactions (max_depth=2)",
        fontsize=16, fontweight="bold",
    )
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    _save(fig, out_dir, "seed_gallery")


# ── Save helper ───────────────────────────────────────────────────────────────

def _save(fig, out_dir, name):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    p = out_dir / f"{name}.png"
    fig.savefig(str(p), dpi=200, bbox_inches="tight")
    print(f"  saved -> {p}")
    plt.close(fig)


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--net-cache", default=str(DEFAULT_NET_CACHE),
                        help="Path to networks_cache .pkl (default: data/networks_cache_LI-Small_Trans_v2.pkl)")
    parser.add_argument("--gen-cache", default=str(DEFAULT_GEN_CACHE),
                        help="Path to gen_cache .pkl (default: data/gen_cache_LI-Small_Trans_n500_...pkl)")
    parser.add_argument("--out",       default="figures_real",
                        help="Output directory (default: figures_real/)")
    parser.add_argument("--seed",      type=int, default=42,
                        help="Random seed for example selection")
    parser.add_argument("--n-rows",    type=int, default=3,
                        help="Rows in pipeline figure (default 4)")
    args = parser.parse_args()

    networks = load_network_cache(args.net_cache)
    gen_data = load_gen_cache(args.gen_cache)

    # Generate fresh graphs so per-node laundering labels come from the model,
    # not from a betweenness proxy.  n_rows for the pipeline + 3×3 for gallery.
    n_needed = args.n_rows + 3 * 3
    print("\nRunning guided generation for per-node labels ...")
    gen_labeled = generate_with_labels(networks, n_gen=n_needed, seed=args.seed)
    if gen_labeled is None:
        print("  [fallback] Using betweenness centrality as laundering proxy.")

    print("\nGenerating pipeline figure ...")
    make_pipeline_figure(networks, gen_data, gen_labeled, args.out,
                         n_rows=args.n_rows, seed=args.seed)

    print("Generating generated gallery ...")
    # Use a fresh slice so pipeline and gallery show different generated graphs
    gallery_labeled = (gen_labeled[args.n_rows:] if gen_labeled else None)
    make_generated_gallery(gen_data, gallery_labeled, args.out, seed=args.seed)

    print("Generating seed gallery ...")
    make_seed_gallery(networks, args.out, seed=args.seed)

    print(f"\nDone. Figures written to '{args.out}/'")


if __name__ == "__main__":
    main()
